# HIMECHAN: build the tankbuster cast-id list from cactbot's raidboss triggers (Apache-2.0, data only).
# A cast id qualifies when a trigger of type StartsUsing answers with a tank response
# (Responses.tankBuster / tankBusterSwap / tankCleave / sharedTankBuster / miniBuster) or prints a
# tankbuster/tankcleave output string. Headmarker-based busters are not casts and are covered in game by
# RSR's lockon-VFX detection, so they are skipped here.
# Usage: cactbot-tankbusters.ps1 -CactbotDir <checkout> -OutPath RotationSolver/Himechan/Localization/HimechanCactbotTankbusters.cs
param(
    [Parameter(Mandatory)] [string]$CactbotDir,
    [Parameter(Mandatory)] [string]$OutPath
)

$ErrorActionPreference = 'Stop'
$dataDir = Join-Path $CactbotDir 'ui/raidboss/data'
if (-not (Test-Path $dataDir)) { throw "cactbot data dir not found: $dataDir" }

$commit = (git -C $CactbotDir log -1 --format='%h %ad' --date=short).Trim()
$triggerRegex = [regex]'(?s)\{\s*\n\s{6}id: ''(?<tid>[^'']+)'',(?<body>.*?)\n\s{4}\},'
$tankResponse = [regex]'Responses\.(tankBuster|tankBusterSwap|tankCleave|sharedTankBuster|miniBuster)\('
$tankOutput = [regex]'Outputs\.\w*(?i:tankbuster|tankcleave|sharedbuster)\w*'
$idList = [regex]'netRegex:\s*\{[^}]*?\bid:\s*(?<ids>''[0-9A-Fa-f]+''|\[[^\]]+\])'

$found = @{}   # id(uint) -> list of "file:trigger"
foreach ($file in Get-ChildItem $dataDir -Recurse -Filter *.ts) {
    $text = Get-Content $file.FullName -Raw -Encoding UTF8
    foreach ($m in $triggerRegex.Matches($text)) {
        $body = $m.Groups['body'].Value
        if ($body -notmatch "type:\s*'StartsUsing'") { continue }
        if (-not ($tankResponse.IsMatch($body) -or $tankOutput.IsMatch($body))) { continue }
        $im = $idList.Match($body)
        if (-not $im.Success) { continue }
        $ids = [regex]::Matches($im.Groups['ids'].Value, '''([0-9A-Fa-f]+)''') | ForEach-Object { $_.Groups[1].Value }
        $rel = $file.FullName.Substring($dataDir.Length + 1).Replace('\', '/')
        foreach ($hex in $ids) {
            $id = [Convert]::ToUInt32($hex, 16)
            if (-not $found.ContainsKey($id)) { $found[$id] = New-Object System.Collections.Generic.List[string] }
            $found[$id].Add("$rel : $($m.Groups['tid'].Value)")
        }
    }
}

$sorted = $found.Keys | Sort-Object
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated> by .github/himechan/cactbot-tankbusters.ps1 - do not edit by hand.')
[void]$sb.AppendLine("// Source: OverlayPlugin/cactbot $commit, ui/raidboss/data (Apache-2.0). $($sorted.Count) cast ids.")
[void]$sb.AppendLine('namespace RotationSolver.Himechan;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('/// <summary>Enemy cast ids that cactbot announces as tankbusters (StartsUsing triggers). Used by the Aquaveil logic.</summary>')
[void]$sb.AppendLine('internal static class HimechanCactbotTankbusters')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine("`tinternal const string Source = `"cactbot $commit`";")
[void]$sb.AppendLine('')
[void]$sb.AppendLine("`tinternal static readonly HashSet<uint> CastIds =")
[void]$sb.AppendLine("`t[")
foreach ($id in $sorted) {
    $where = ($found[$id] | Select-Object -First 2) -join '; '
    [void]$sb.AppendLine("`t`t$id, // 0x$($id.ToString('X')) $where")
}
[void]$sb.AppendLine("`t];")
[void]$sb.AppendLine('}')
[IO.File]::WriteAllText($OutPath, $sb.ToString(), [Text.UTF8Encoding]::new($false))
"wrote $OutPath : $($sorted.Count) cast ids from cactbot $commit"
