namespace RotationSolver.Himechan;

/// <summary>Korean dictionary, keyed by RSR's English text. Part 1: UiString descriptions (Data/UiString.cs).</summary>
internal static partial class HimechanKoreanStrings
{
	internal static readonly Dictionary<string, string> Map = new(StringComparer.Ordinal);

	static HimechanKoreanStrings()
	{
		AddUiStrings();
		AddConfigNames();
		AddConfigDescriptions();
	}

	private static void Add(string english, string korean)
	{
		Map[english] = korean;
	}

	private static void AddUiStrings()
	{
		Add("The condition value you chose. Click to modify.", "선택한 조건 값입니다. 클릭하면 수정합니다.");
		Add("Condition Value", "조건 값");
		Add("Action Condition", "기술 조건");
		Add("Trait Condition", "특성 조건");
		Add("Target Condition", "대상 조건");
		Add("Rotation Condition", "로테이션 조건");
		Add("Named Condition", "이름 있는 조건");
		Add("Territory Condition", "지역 조건");
		Add("No rotations loaded! Please check the rotations tab!", "불러온 로테이션이 없습니다! 로테이션 탭을 확인하세요!");
		Add("Current duty logic.", "현재 임무 로직입니다.");
		Add("Remove", "제거");
		Add("Load from folder", "폴더에서 불러오기");
		Add("Analyzes PvE combat information in every frame and finds the best action.", "매 프레임 PvE 전투 정보를 분석해 가장 좋은 행동을 찾습니다.");
		Add("Invalid Rotation! \nPlease update to the latest version or contact {0}!", "잘못된 로테이션입니다! \n최신 버전으로 업데이트하거나 {0}에게 문의하세요!");
		Add("Click to switch rotations", "클릭하여 로테이션 전환");
		Add("Search Result", "검색 결과");
		Add("Health thresholds", "HP 기준값");
		Add("Minimum", "최소");
		Add("Maximum", "최대");
		Add("This includes almost all information available in one combat frame, including the status of all party members, hostile target statuses, skill cooldowns, MP and HP of characters, character locations, hostile target casting status, combo state, combat duration, player level, etc.\n\nIt will then highlight the best action on the hotbar, or help you click it.", "한 전투 프레임에서 얻을 수 있는 거의 모든 정보를 사용합니다. 파티원 전원의 상태, 적 대상의 상태, 기술 재사용 대기시간, 캐릭터의 MP와 HP, 위치, 적의 시전 상태, 콤보 상태, 전투 시간, 플레이어 레벨 등입니다.\n\n그다음 핫바에서 가장 좋은 행동을 강조 표시하거나, 대신 눌러 줍니다.");
		Add("This is designed for general combat, with optimizations for savage/ultimate content needing to be hand tuned. \n\nBe mindful of your usage in savage/ultimate content.", "일반 전투용으로 설계되었으며, 영식·절 콘텐츠 최적화는 직접 손봐야 합니다. \n\n영식·절 콘텐츠에서는 사용에 주의하세요.");
		Add("RSR has helped you by clicking actions {0:N0} times.", "RSR이 지금까지 행동을 {0:N0}번 대신 눌러 드렸습니다.");
		Add("State Macros", "상태 매크로");
		Add("Action and Setting Macros", "기술·설정 매크로");
		Add("Compatibility", "호환성");
		Add("Supporters", "후원자");
		Add("Links", "링크");
		Add("System Warnings", "시스템 경고");
		Add("Warning Message", "경고 메시지");
		Add("Warning Time", "경고 시각");
		Add("Rotation Solver helps you choose targets and click actions. Any plugin that changes these will affect its decisions.\n\nHere is a list of plugins that have historically (but not always) caused compatibility issues:", "Rotation Solver는 대상 선택과 기술 사용을 돕습니다. 이를 바꾸는 플러그인은 판단에 영향을 줍니다.\n\n과거에(항상은 아니지만) 호환성 문제를 일으킨 플러그인 목록입니다:");
		Add("Cannot properly execute the behavior that RSR wants to perform.", "RSR이 하려는 동작을 제대로 실행하지 못하게 합니다.");
		Add("Conflicts with RSR decision-making", "RSR의 판단과 충돌합니다");
		Add("Causes the game to crash", "게임을 멈추게 합니다");
		Add("Many thanks to Ko-fi sponsors.", "Ko-fi 후원자 여러분께 감사드립니다.");
		Add("Open Config Folder", "설정 폴더 열기");
		Add("Description", "설명");
		Add("Configuration", "설정");
		Add("Duty Configuration", "임무 설정");
		Add("Status", "상태");
		Add("Duty Rotation Status", "임무 로테이션 상태");
		Add("Used to customize when RSR uses specific actions automatically. Click on an action's icon in the left list. Below, you may set the conditions for when that specific action is used. Each action can have different conditions to override the default rotation behavior.", "RSR이 특정 기술을 언제 자동으로 쓸지 정합니다. 왼쪽 목록에서 기술 아이콘을 클릭하고, 아래에서 그 기술의 사용 조건을 설정하세요. 기술마다 다른 조건을 두어 기본 로테이션 동작을 덮어쓸 수 있습니다.");
		Add("Allow action to be intercepted by the intercept system", "가로채기 시스템이 이 기술을 가로채도록 허용");
		Add("Prevent this action against a curated list of mobs (ie. Jagd Dolls)", "지정된 몬스터 목록(예: 야크트 돌)에는 이 기술을 쓰지 않음");
		Add("Allow action to be restricted by the minimum HP feature", "최소 HP 기능으로 이 기술을 제한하도록 허용");
		Add("If target is below this percent, do not use this action", "대상 HP가 이 비율보다 낮으면 이 기술을 쓰지 않음");
		Add("Skip BossModReborn position-safety check for this movement action", "이 이동 기술에는 BossModReborn 위치 안전 검사를 생략");
		Add("Time-to-kill threshold required for this action to be used", "이 기술을 쓰기 위한 예상 처치 시간(TTK) 기준값");
		Add("Number of targets needed to use this action", "이 기술을 쓰기 위한 대상 수");
		Add("Should this action check needed status effects", "이 기술이 필요한 상태 효과를 확인할지");
		Add("Should this action check targets needed status effects", "이 기술이 대상에게 필요한 상태 효과를 확인할지");
		Add("Number of GCDs before the DOT/Status effect is reapplied", "DoT·상태 효과를 다시 걸기까지의 GCD 수");
		Add("HP ratio for automatic healing (only applies to healing actions)", "자동 회복을 시작할 HP 비율(회복 기술에만 적용)");
		Add("Forced Conditions have higher priority. If Forced Conditions are met, Disabled Conditions will be ignored.", "강제 조건이 우선합니다. 강제 조건을 만족하면 비활성 조건은 무시됩니다.");
		Add("Forced Condition (Unsupported)", "강제 조건(지원 종료)");
		Add("Conditions for forced automatic use of action", "기술을 강제로 자동 사용할 조건");
		Add("Disabled Condition (Unsupported)", "비활성 조건(지원 종료)");
		Add("Conditions that disable automatic use of an action", "기술의 자동 사용을 막을 조건");
		Add("In this window, you can set parameters that can be customized using lists.", "이 창에서는 목록으로 관리하는 설정값을 바꿀 수 있습니다.");
		Add("Statuses", "상태 효과");
		Add("Actions", "기술");
		Add("Map-specific settings", "지역별 설정");
		Add("Status name or ID", "상태 효과 이름 또는 ID");
		Add("Invulnerability", "무적");
		Add("Priority", "우선 대상");
		Add("Dispellable debuffs", "해제 가능한 디버프");
		Add("No-casting debuffs", "시전 금지 디버프");
		Add("Ignores target if it has one of these statuses", "이 상태 효과 중 하나가 있는 대상은 무시합니다");
		Add("Attacks the target first if it has one of these statuses", "이 상태 효과 중 하나가 있는 대상을 먼저 공격합니다");
		Add("Dispellable debuffs list", "해제 가능한 디버프 목록");
		Add("Do not take action if you have one of these debuffs", "이 디버프 중 하나가 걸려 있으면 행동하지 않습니다");
		Add("Copy to Clipboard", "클립보드에 복사");
		Add("From Clipboard", "클립보드에서");
		Add("Add Status", "상태 효과 추가");
		Add("Action name or ID", "기술 이름 또는 ID");
		Add("Tank Buster", "탱커버스터");
		Add("AoE", "광역 공격");
		Add("Knockback", "넉백");
		Add("Gaze/Stop", "시선/정지");
		Add("Use tank personal damage mitigation abilities if the target is casting any of these actions", "대상이 이 기술 중 하나를 시전하면 탱커 개인 경감 기술을 사용합니다");
		Add("Use AoE damage mitigation abilities if the target is casting any of these actions", "대상이 이 기술 중 하나를 시전하면 광역 경감 기술을 사용합니다");
		Add("Use knockback prevention abilities if the target is casting any of these actions", "대상이 이 기술 중 하나를 시전하면 넉백 방지 기술을 사용합니다");
		Add("Stop casting or taking actions if the enemy is casting this ability", "적이 이 기술을 시전하면 시전과 행동을 멈춥니다");
		Add("Add Action", "기술 추가");
		Add("Don't target", "대상으로 삼지 않음");
		Add("Don't provoke", "도발하지 않음");
		Add("Beneficial AoE locations", "이로운 광역 효과 위치");
		Add("Enemies that will never be targeted", "절대 대상으로 삼지 않을 적");
		Add("The name of the enemy that you don't want to target", "대상으로 삼고 싶지 않은 적의 이름");
		Add("Enemies that will never be provoked", "절대 도발하지 않을 적");
		Add("The name of the enemy that you don't want to provoke", "도발하고 싶지 않은 적의 이름");
		Add("Add beneficial AoE location", "이로운 광역 효과 위치 추가");
		Add("Ability", "능력");
		Add("Friendly", "아군");
		Add("Attack", "공격");
		Add("Normal Targets", "일반 대상");
		Add("Targets with Heal-over-Time", "지속 회복이 걸린 대상");
		Add("HP threshold for AoE healing oGCDs", "광역 회복 oGCD의 HP 기준값");
		Add("HP threshold for AoE healing GCDs", "광역 회복 GCD의 HP 기준값");
		Add("HP threshold for single-target healing oGCDs", "단일 회복 oGCD의 HP 기준값");
		Add("HP threshold for single-target healing GCDs", "단일 회복 GCD의 HP 기준값");
		Add("No Move", "이동 잠금");
		Add("Move", "이동");
		Add("Setting Search", "설정 검색");
		Add("Timer", "타이머");
		Add("Auto Switch", "자동 전환");
		Add("Named Conditions", "이름 있는 조건");
		Add("Others", "기타");
		Add("The animation lock time for individual actions. For example, 0.6s.", "기술별 애니메이션 잠금 시간입니다. 예: 0.6초.");
		Add("The clicking duration - RSR will try to click at this moment.", "클릭 시점 - RSR이 이 시점에 누르려고 합니다.");
		Add("The ideal click time", "이상적인 클릭 시각");
		Add("The actual click time", "실제 클릭 시각");
		Add("Auto turn-off conditions", "자동 끄기 조건");
		Add("Auto manual mode conditions", "자동 수동 모드 조건");
		Add("Auto automatic mode conditions", "자동 자동 모드 조건");
		Add("Condition Name", "조건 이름");
		Add("Information", "정보");
		Add("Overlay", "오버레이");
		Add("Windows", "창");
		Add("Change how RSR automatically uses actions", "RSR이 기술을 자동으로 쓰는 방식을 바꿉니다");
		Add("Action Usage and Control", "기술 사용과 제어");
		Add("Which actions RSR can use", "RSR이 쓸 수 있는 기술");
		Add("Healing Usage and Control", "회복 사용과 제어");
		Add("How RSR should use healing abilities", "RSR이 회복 기술을 쓰는 방식");
		Add("Custom State Condition (Unsupported)", "사용자 상태 조건(지원 종료)");
		Add("Heal Area Forced Condition", "광역 회복 강제 조건");
		Add("Heal Single Forced Condition", "단일 회복 강제 조건");
		Add("Defense Area Forced Condition", "광역 방어 강제 조건");
		Add("Defense Single Forced Condition", "단일 방어 강제 조건");
		Add("Dispel/Stance/Positional Forced Condition", "디스펠/자세/방향 공격 강제 조건");
		Add("Raise/Shirk Forced Condition", "부활/책임 전가 강제 조건");
		Add("Move Forward Forced Condition", "전진 이동 강제 조건");
		Add("Move Back Forced Condition", "후방 이동 강제 조건");
		Add("Anti-Knockback Forced Condition", "넉백 방지 강제 조건");
		Add("Speed Forced Condition", "이동 속도 강제 조건");
		Add("No Casting Condition Set", "시전 금지 조건 집합");
		Add("This will change how RSR uses actions", "RSR이 기술을 쓰는 방식이 바뀝니다");
		Add("Hostile", "적");
		Add("Enemy targeting logic. Adding more options cycles them when using /rotation Auto.\nUse /rotation Settings TargetingTypes add <option> to add,\n/rotation Settings TargetingTypes remove <option> to remove,\nand /rotation Settings TargetingTypes removeall to remove all options.", "적 대상 선택 로직입니다. 여러 개를 추가하면 /rotation Auto 명령마다 순환합니다.\n추가: /rotation Settings TargetingTypes add <옵션>\n제거: /rotation Settings TargetingTypes remove <옵션>\n전부 제거: /rotation Settings TargetingTypes removeall");
		Add("Add targeting priority", "대상 우선순위 추가");
		Add("Move Up", "위로");
		Add("Move Down", "아래로");
		Add("Hostile target selection condition", "적 대상 선택 조건");
		Add("RSR focuses on the rotation itself. These are side features. Subject to removal at any time.", "RSR의 핵심은 로테이션입니다. 여기는 부가 기능이며 언제든 제거될 수 있습니다.");
		Add("Event", "이벤트");
		Add("Internal", "내부");
		Add("Add Events", "이벤트 추가");
		Add("In this window, you can set which macro will be triggered after using an action.", "이 창에서는 기술 사용 후 실행할 매크로를 정합니다.");
		Add("Duty Start: ", "임무 시작: ");
		Add("Duty End: ", "임무 종료: ");
		Add("Delete Event", "이벤트 삭제");
		Add("Click to make it reverse.\nIs reversed: {0}", "클릭하면 반전합니다.\n반전됨: {0}");
		Add("Member Name", "멤버 이름");
		Add("Rotation is null. Please log in or switch jobs!", "로테이션이 없습니다. 로그인하거나 직업을 바꿔 보세요!");
		Add("Ultimate", "절");
		Add("Savage", "영식");
		Add("Chaotic Alliance Raid", "카오틱 얼라이언스 레이드");
		Add("Extreme", "극");
		Add("Dungeon", "던전");
		Add("Deep Dungeon", "심층 던전");
		Add("Variant Dungeon", "변형 던전");
		Add("Treasure Dungeon", "보물 던전");
		Add("Alliance Raid", "얼라이언스 레이드");
		Add("Field Ops", "필드 작전");
		Add("PvP", "PvP");
		Add("The Masked Carnivale", "가면 축제");
		Add("Crucible of the Unbroken", "불굴의 도가니(Crucible of the Unbroken)");
		Add("Delay its transition to true", "참으로 바뀌는 시점을 지연");
		Add("Delay its transition", "전환 시점을 지연");
		Add("Sufficient Level", "레벨 충족");
		Add("Time Offset", "시간 오프셋");
		Add("Charges", "충전");
		Add("Original", "원본");
		Add("Adjusted", "조정됨");
		Add("{0}'s target", "{0}의 대상");
		Add("From All", "모두에게서");
		Add("From Self", "자신에게서");
		Add("You should not use this, as this target isn't the action's target. Try selecting it from the action instead.", "이 대상은 기술의 대상이 아니므로 쓰지 않는 것이 좋습니다. 기술 쪽에서 선택해 보세요.");
		Add("Territory Name", "지역 이름");
		Add("Duty Name", "임무 이름");
		Add("Please separately bind damage reduction/shield cooldowns in case RSR fails at a crucial moment in {0}!", "{0}에서 결정적인 순간에 RSR이 실패할 수 있으니 경감·보호막 기술은 따로 단축키에 두세요!");
		Add("Click to execute the command", "클릭하면 명령을 실행합니다");
		Add("Right-click to copy the command", "우클릭하면 명령을 복사합니다");
		Add("Macro No.", "매크로 번호");
		Add("Is Shared", "공용 여부");
		Add("Action Name", "기술 이름");
		Add("Modify {0} to {1}", "{0}을(를) {1}(으)로 변경");
		Add("Failed to find the config in this rotation. Please check it.", "이 로테이션에서 해당 설정을 찾지 못했습니다. 확인해 주세요.");
		Add("Will use it within {0}s", "{0}초 안에 사용합니다");
		Add("Cannot find the action. Please check the action name.", "기술을 찾을 수 없습니다. 기술 이름을 확인해 주세요.");
		Add("Failed to get both value and config from string. Please make sure you provide both a config option and value.", "문자열에서 설정과 값을 모두 읽지 못했습니다. 설정 이름과 값을 함께 적었는지 확인하세요.");
		Add("Start", "시작");
		Add("Cancel", "취소");
		Add("Heal Area", "광역 회복");
		Add("Heal Single", "단일 회복");
		Add("Defense Area", "광역 방어");
		Add("Defense Single", "단일 방어");
		Add("Tank Stance", "탱커 자세");
		Add("Dispel", "디스펠");
		Add("Positional", "방향 공격");
		Add("Shirk", "책임 전가");
		Add("Raise", "부활");
		Add("Move Forward", "전진 이동");
		Add("Move Back", "후방 이동");
		Add("Anti-Knockback", "넉백 방지");
		Add("Burst", "버스트");
		Add("End Special", "특수 상태 종료");
		Add("Speed", "이동 속도");
		Add("Limit Break", "리미트 브레이크");
		Add("No Casting", "시전 금지");
		Add("Auto Target", "자동 대상");
		Add("Manual Target", "수동 대상");
		Add("Off", "끄기");
		Add("Open config window", "설정 창 열기");
		Add("Start RSR combat rotation state", "RSR 전투 로테이션 상태 시작");
		Add("Disable RSR combat rotation state", "RSR 전투 로테이션 상태 끄기");
		Add("Rotation Solver Reborn Settings v", "Rotation Solver Reborn 설정 v");
		Add("This config is job-specific", "이 설정은 직업별로 저장됩니다");
		Add("This option is unavailable with your current job\n \nRoles or jobs needed:\n{0}", "현재 직업에서는 쓸 수 없는 설정입니다\n \n필요한 역할 또는 직업:\n{0}");
		Add("Welcome to Rotation Solver Reborn!", "Rotation Solver Reborn에 오신 것을 환영합니다!");
		Add("Here's what you missed since you were last here", "지난 방문 이후 바뀐 내용입니다");
		Add("It looks like you might be new here! Let's get you started!", "처음 오신 것 같네요! 시작을 도와드릴게요!");
		Add("Recent Changes:", "최근 변경 사항:");
	}
}
