namespace RotationSolver.Himechan;

/// <summary>Korean dictionary part 2: setting names and descriptions ([UI(...)] in Configuration/Configs.cs).</summary>
internal static partial class HimechanKoreanStrings
{
	private static void AddConfigNames()
	{
		Add("Prevent specific Flat Damage/Death actions from being used against mobs that are immune to those effects.", "고정 피해/즉사 기술을 해당 효과에 면역인 몬스터에게 쓰지 않음");
		Add("Prevent specific Slow actions from being used against mobs that are immune to those effects.", "둔화 기술을 해당 효과에 면역인 몬스터에게 쓰지 않음");
		Add("Prevent specific Petrification actions from being used against mobs that are immune to those effects.", "석화 기술을 해당 효과에 면역인 몬스터에게 쓰지 않음");
		Add("Prevent specific Paralysis actions from being used against mobs that are immune to those effects.", "마비 기술을 해당 효과에 면역인 몬스터에게 쓰지 않음");
		Add("Prevent specific Interrupt actions from being used against mobs that are immune to those effects.", "시전 방해 기술을 해당 효과에 면역인 몬스터에게 쓰지 않음");
		Add("Prevent specific Blind actions from being used against mobs that are immune to those effects.", "실명 기술을 해당 효과에 면역인 몬스터에게 쓰지 않음");
		Add("Prevent specific Stun actions from being used against mobs that are immune to those effects.", "기절 기술을 해당 효과에 면역인 몬스터에게 쓰지 않음");
		Add("Prevent specific Sleep actions from being used against mobs that are immune to those effects.", "수면 기술을 해당 효과에 면역인 몬스터에게 쓰지 않음");
		Add("Prevent specific Bind actions from being used against mobs that are immune to those effects.", "속박 기술을 해당 효과에 면역인 몬스터에게 쓰지 않음");
		Add("Prevent specific Heavy actions from being used against mobs that are immune to those effects.", "과중 기술을 해당 효과에 면역인 몬스터에게 쓰지 않음");
		Add("Prevent specific aspected actions from being used against mobs that are immune to that aspect.", "속성 기술을 그 속성에 면역인 몬스터에게 쓰지 않음");
		Add("If a mob is weak to a specific aspect, only use actions of that aspect.", "몬스터가 특정 속성에 약하면 그 속성 기술만 사용");
		Add("Still allow unaspected actions.", "무속성 기술은 계속 허용");
		Add("O12S - Packet Filter logic.", "O12S - 패킷 필터 로직");
		Add("M8S - Wolf Pack/Stone Pack logic.", "M8S - 바람 늑대/돌 늑대 로직");
		Add("M9S - Only use cleave logic.", "M9S - 단일 광역(클리브)만 사용 로직");
		Add("M9S - Cell Targeting logic.", "M9S - 세포 대상 로직");
		Add("M9S - Ads Targeting logic.", "M9S - 쫄 대상 로직");
		Add("M10S - Firesnaking/Watersnaking targeting logic.", "M10S - 불뱀/물뱀 대상 로직");
		Add("Limitless Blue Extreme - Whaleback logic.", "극 비스마르크 - 고래등 로직");
		Add("Cinder Drift Extreme - Pall Targeting logic.", "극 루비 웨폰 - 장막 대상 로직");
		Add("The Unmaking Extreme - Shadow logic.", "극 언메이킹 - 그림자 로직");
		Add("The Epic of Alexander (Ultimate) - Jagd Doll logic.", "절 알렉산더 - 야크트 돌 로직");
		Add("The Epic of Alexander (Ultimate) - True Heart logic.", "절 알렉산더 - 진심 로직");
		Add("The Omega Protocol (Ultimate) - Packet Filter logic.", "절 오메가 - 패킷 필터 로직");
		Add("Futures Rewritten (Ultimate) - Crystal Of Darkness logic.", "절 에덴 - 어둠의 크리스탈 로직");
		Add("Dancing Mad (Ultimate) - Hero/Villain logic.", "절 Dancing Mad - 영웅/악당 로직");
		Add("The Ghimlyt Dark - Colossus Rubricatus ad.", "김리트 황야 - 콜로서스 루브리카투스 쫄");
		Add("Dohn Mheg - Liars Lyre mechancic.", "돈 메그 - 거짓말쟁이의 수금 기믹");
		Add("The Meso Terminal - Thanatos logic.", "메소 터미널 - 타나토스 로직");
		Add("Forked Tower Blood - Dead Star logic.", "갈림탑 혈 - 죽은 별 로직");
		Add("Forked Tower Magic - First Boss Villian/Hero.", "갈림탑 마 - 1보스 악당/영웅");
		Add("North Horn CE - Tiny Mage targetting logic.", "North Horn CE - 꼬마 마도사 대상 로직");
		Add("Elemental Weakness Tracking.", "속성 약점 추적");
		Add("Pilgrim's Traverse - Eminent Grief logic.", "순례자의 길 - 비탄 로직");
		Add("The Labyrinth of the Ancients - Thanatos logic.", "고대의 미궁 - 타나토스 로직");
		Add("The Void Ark - Irminsul and Sawtooth logic.", "보이드 방주 - 이르민술과 톱니 로직");
		Add("The Puppets' Bunker - Superior Flight Unit logic.", "인형들의 벙커 - 상위 비행 유닛 로직");
		Add("The Tower at Paradigm's Breach - Hansel and Gretel logic.", "패러다임 돌파탑 - 헨젤과 그레텔 로직");
		Add("Jeuno: The First Walk - The Ark Angels logic.", "주노: 첫 번째 행보 - 방주의 천사 로직");
		Add("Windurst: The Third Walk - Alexander Resurrected logic.", "윈더스트: 세 번째 행보 - 부활한 알렉산더 로직");
		Add("Cloud of Darkness - Ads phase logic.", "어둠의 구름 - 쫄 페이즈 로직");
		Add("The Sil'dihn Subterrane - Drakefamily ads logic.", "실디하 지하 - 드레이크 일족 쫄 로직");
		Add("Treasure Dungeons - Timed mob logic.", "보물 던전 - 시간제한 몬스터 로직");
		Add("Treasure Dungeons - Numbered mob logic.", "보물 던전 - 번호 몬스터 로직");
		Add("The HP for using Guard.", "가드를 쓸 HP");
		Add("Ignore TTK for PvP purposes.", "PvP에서는 예상 처치 시간(TTK) 무시");
		Add("Prioritize A tier tomeliths in Shatter.", "쉐터에서 A급 토멜리스 우선");
		Add("Prioritize B tier tomeliths in Shatter.", "쉐터에서 B급 토멜리스 우선");
		Add("Ignore Invincibility for PvP purposes.", "PvP에서는 무적 무시");
		Add("Auto turn off when dead in PvP.", "PvP에서 사망하면 자동으로 끄기");
		Add("Auto turn off when PvP match ends.", "PvP 경기가 끝나면 자동으로 끄기");
		Add("Auto turn on when PvP match starts.", "PvP 경기가 시작되면 자동으로 켜기");
		Add("Set RSR to PvP specific state when enabled in PvP zone.", "PvP 지역에서 켜면 RSR을 PvP 전용 상태로 설정");
		Add("Don't use any actions while in Guard.", "가드 중에는 어떤 기술도 쓰지 않음");
		Add("Cancel cast in PvP if the target gains Guard and the action does not ignore Guard.", "PvP에서 대상이 가드를 켜고 기술이 가드를 무시하지 않으면 시전 취소");
		Add("Use Purify to remove Stun debuff", "기절 디버프를 정화로 해제");
		Add("Use Purify to remove Silence debuff", "침묵 디버프를 정화로 해제");
		Add("Use Purify to remove Deep Freeze debuff", "빙결 디버프를 정화로 해제");
		Add("Use Purify to remove Miracle of Nature debuff", "자연의 기적 디버프를 정화로 해제");
		Add("Use Purify to remove Heavy debuff", "과중 디버프를 정화로 해제");
		Add("Use Purify to remove Bind debuff", "속박 디버프를 정화로 해제");
		Add("Lock out GCD cycle if you are below 50% HP and have over 2000 MP for heals (Experimental).", "HP 50% 미만이고 MP가 2000 이상이면 회복을 위해 GCD 순환 잠금(실험적)");
		Add("Allow Sprint when no target is set even if youre in range of hostiles (Experimental).", "대상이 없으면 적 사거리 안에서도 전력 질주 허용(실험적)");
		Add("Use BMR intergration to verify safety of movement actions/actions that cause movement for automatic usage. (Experimental)", "자동 사용 시 이동 기술·이동이 생기는 기술의 안전을 BMR 연동으로 확인(실험적)");
		Add("Use BMR intergration to verify safety of movement actions/actions that cause movement for intercepted usage. (Experimental)", "가로챈 입력의 이동 기술·이동이 생기는 기술의 안전을 BMR 연동으로 확인(실험적)");
		Add("Intercept player input and queue it for RSR to execute the action. (PvE only)", "플레이어 입력을 가로채 RSR이 대신 실행하도록 대기열에 넣음(PvE 전용)");
		Add("Allow intercepting Spells.", "마법 가로채기 허용");
		Add("Allow intercepting Weaponskills.", "무기 기술 가로채기 허용");
		Add("Allow intercepting Abilities.", "능력 가로채기 허용");
		Add("Allow intercepting actions in macros.", "매크로 안의 기술 가로채기 허용");
		Add("Allow intercepting actions that are currently on cooldown.", "재사용 대기 중인 기술도 가로채기 허용");
		Add("Pass original player input to action manager. (Enabling this will cause clipping).", "원래 플레이어 입력도 게임에 전달(켜면 GCD 밀림이 생김)");
		Add("Intercepted action execution window (amount of time RSR is allowed to attempt to use an action after it has been intercepted)", "가로챈 기술 실행 허용 시간(가로챈 뒤 RSR이 사용을 시도할 수 있는 시간)");
		Add("Use BossModReborn's Cooldown Planner actions with the interception system (Experimental)", "BossModReborn 쿨다운 플래너의 기술을 가로채기 시스템과 함께 사용(실험적)");
		Add("How far ahead (in seconds) to look up upcoming Cooldown Planner actions", "쿨다운 플래너의 예정 기술을 몇 초 앞까지 볼지");
		Add("What kind of AoE moves to use.", "사용할 광역 기술 종류");
		Add("Ignore status application against mobs that are status capped.", "상태 효과 한도에 걸린 몬스터에게는 상태 효과 부여 무시");
		Add("Don't attack new mobs by AoE.", "광역 기술로 새 몬스터를 건드리지 않음");
		Add("Disable automatically during area transitions.", "지역 이동 중 자동으로 끄기");
		Add("Disable automatically during cutscenes.", "컷신 중 자동으로 끄기");
		Add("Auto turn off when switching jobs", "직업을 바꾸면 자동으로 끄기");
		Add("Auto turn off when dead in PvE.", "PvE에서 사망하면 자동으로 끄기");
		Add("Auto turn off when duty is completed.", "임무가 끝나면 자동으로 끄기");
		Add("Enable changelog window popup on update", "업데이트 시 변경 사항 창 표시");
		Add("Show plugin status in DTR bar.", "서버 정보 표시줄(DTR)에 플러그인 상태 표시");
		Add("DTR Behaviour", "DTR 동작");
		Add("Display plugin status in toast popup", "플러그인 상태를 알림(토스트)으로 표시");
		Add("Lock movement when casting or performing certain actions.", "시전 중이거나 특정 기술을 쓸 때 이동 잠금");
		Add("Unlock movement when pressing both left and right mouse buttons.", "마우스 양쪽 버튼을 함께 누르면 이동 잠금 해제");
		Add("Lock actions when casting Passage Of Arms during AOE mitigations.", "광역 경감 중 Passage of Arms 시전 동안 기술 잠금");
		Add("Lock actions when casting Collective Unconscious during AOE mitigations.", "광역 경감 중 집단 무의식 시전 동안 기술 잠금");
		Add("Lock actions when casting Phantom Flurry.", "Phantom Flurry 시전 동안 기술 잠금");
		Add("Only used automatically if coded into the rotation", "로테이션에 구현된 경우에만 자동 사용");
		Add("Automatically use Anti-Knockback role actions (Arms Length, Surecast)", "넉백 방지 역할 기술(Arm's Length, Surecast) 자동 사용");
		Add("Automatically use HP Potions", "HP 물약 자동 사용");
		Add("Use HP Potions when HP% is lower than this", "HP%가 이 값보다 낮으면 HP 물약 사용");
		Add("Automatically use MP Potions", "MP 물약 자동 사용");
		Add("Use MP Potions when MP% is lower than this", "MP%가 이 값보다 낮으면 MP 물약 사용");
		Add("Automatically use Phoenix Down", "불사조의 꼬리 자동 사용");
		Add("Use Phoenix Down only if no Raiser alive in party", "파티에 살아 있는 부활 가능 직업이 없을 때만 불사조의 꼬리 사용");
		Add("Use damaging gap closer abilites if the distance to your target is less than this.", "대상과의 거리가 이 값보다 가까우면 피해를 주는 돌진 기술 사용");
		Add("Allow the use of AOEs against priority-marked targets.", "우선 표식이 있는 대상에게 광역 기술 허용");
		Add("Teaching mode", "교습 모드");
		Add("Auto-target in teaching mode while in combat", "교습 모드에서 전투 중 자동 대상 지정");
		Add("Show target hint in Next Action window", "다음 행동 창에 대상 힌트 표시");
		Add("Simulate the effect of pressing abilities", "기술을 누르는 효과 흉내 내기");
		Add("Activate auto mode when countdown starts", "카운트다운이 시작되면 자동 모드 켜기");
		Add("Start manual mode instead of auto mode when countdown starts", "카운트다운 시작 시 자동 모드 대신 수동 모드로 시작");
		Add("Cancel auto mode if combat starts early during countdown", "카운트다운 중 전투가 일찍 시작되면 자동 모드 취소");
		Add("I understand that Auto On settings will turn RSRs autorotation on, automatically.", "자동 켜기 설정이 RSR 자동 로테이션을 스스로 켠다는 것을 이해합니다.");
		Add("Auto turn on manual mode when attacked.", "공격받으면 수동 모드 자동 켜기");
		Add("Auto turn on auto mode when party is in combat.", "파티가 전투 중이면 자동 모드 자동 켜기");
		Add("Auto turn on auto mode when alliance is in combat.", "얼라이언스가 전투 중이면 자동 모드 자동 켜기");
		Add("Auto turn on auto mode when in combat in Bozja/Eureka/Occult Fate/CE", "보즈야/에우레카/오컬트 FATE/CE에서 전투 중이면 자동 모드 자동 켜기");
		Add("Use healing abilities when playing a non-healer role.", "힐러가 아닌 역할에서도 회복 기술 사용");
		Add("Use interrupt abilities if possible.", "가능하면 시전 방해 기술 사용");
		Add("Provoke anything not on the no provoke list.", "도발 금지 목록에 없는 모든 적 도발");
		Add("Stop casting if the target dies.", "대상이 죽으면 시전 중지");
		Add("Cleanse all dispellable debuffs regardless of healing.", "회복 상황과 관계없이 해제 가능한 디버프는 모두 해제");
		Add("Debug Mode", "디버그 모드");
		Add("Enable Action Tracer (ONLY toggle this at dev request)", "행동 추적기 켜기(개발자가 요청할 때만)");
		Add("Mirror tracer output to Dalamud plugin log", "추적 결과를 Dalamud 플러그인 로그에도 기록");
		Add("Make /rotation Manual a toggle command.", "/rotation Manual을 토글 명령으로");
		Add("Make /rotation Auto a toggle command. (Normal behavior cycles between targeting settings)", "/rotation Auto를 토글 명령으로(기본 동작은 대상 설정 순환)");
		Add("Show State Window", "상태 창 표시");
		Add("Only show these windows if there are enemies or in duty", "적이 있거나 임무 중일 때만 이 창들을 표시");
		Add("Show Control Window", "조작 창 표시");
		Add("Lock Control Window", "조작 창 잠금");
		Add("Show special buttons", "특수 버튼 표시");
		Add("Show Next Action Window", "다음 행동 창 표시");
		Add("Show Intercepted Action Window", "가로챈 행동 창 표시");
		Add("No Inputs", "입력 차단");
		Add("Show Keybind (Experiemental)", "단축키 표시(실험적)");
		Add("Window Size", "창 크기");
		Add("Show Original Cooldown", "원래 재사용 대기시간 표시");
		Add("Always Show Cooldowns", "재사용 대기시간 항상 표시");
		Add("Show tooltips", "도움말 표시");
		Add("Show Action Context Menu Enable/Disable toggle", "기술 우클릭 메뉴에 사용/해제 토글 표시");
		Add("Show random usage hints at top of configuration window", "설정 창 상단에 사용 팁 표시");
		Add("Color disabled actions on hotbars", "핫바에서 해제한 기술에 색 입히기");
		Add("Disabled actions hotbar tint color", "해제한 기술의 핫바 색");
		Add("Show setting descriptions inline", "설정 설명을 이름 아래에 표시");
		Add("Interface accent colour", "인터페이스 강조 색");
		Add("Text size", "글자 크기");
		Add("Element size", "요소 크기");
		Add("Padding", "여백");
		Add("Display do action feedback on toast", "기술 실행 알림을 토스트로 표시");
		Add("Allow rotations that use this config to use abilities defined in the rotation as burst", "이 설정을 쓰는 로테이션이 정의한 버스트 기술 사용 허용");
		Add("Disable hostile actions if something is casting an action on the Gaze/Stop list (EXPERIMENTAL)", "시선/정지 목록의 기술이 시전 중이면 공격 기술 중지(실험적)");
		Add("Configurable amount of time before the cast finishes that RSR stops taking actions", "시전 완료 몇 초 전부터 RSR이 행동을 멈출지");
		Add("Disable for the entire duration (Enabling this will prevent your actions for the entire cast.)", "시전 시간 전체 동안 중지(켜면 시전 내내 행동하지 않음)");
		Add("Automatic Healing Thresholds", "자동 회복 기준값");
		Add("Stop single target GCD healing after reaching threshold. (EXTREMELY Experimental)", "기준값에 도달하면 단일 GCD 회복 중지(매우 실험적)");
		Add("Auto-use oGCD abilities", "oGCD 능력 자동 사용");
		Add("Use defensive actions", "방어 기술 사용");
		Add("Automatically use Single Target defensive actions", "단일 대상 방어 기술 자동 사용");
		Add("Automatically use AOE defensive actions", "광역 방어 기술 자동 사용");
		Add("Use BossModReborn timeline for proactive mitigation", "BossModReborn 타임라인으로 미리 경감");
		Add("Seconds before raidwide to use area mitigation", "광역기 몇 초 전에 광역 경감을 쓸지");
		Add("Seconds before tankbuster to use single mitigation", "탱커버스터 몇 초 전에 단일 경감을 쓸지");
		Add("Seconds before knockback to use anti-knockback", "넉백 몇 초 전에 넉백 방지를 쓸지");
		Add("Number of hostiles", "적 수");
		Add("HP%% needed to use single/self targetted mitigation on Tanks", "탱커에게 단일/자기 대상 경감을 쓸 HP%%");
		Add("Automatically activate tank stance", "탱커 자세 자동 켜기");
		Add("Auto provoke when there is another tank in party", "파티에 다른 탱커가 있으면 자동 도발");
		Add("Auto True North (Melee DPS)", "진북 자동 사용(근접 딜러)");
		Add("Use movement speed increase abilities when out of combat and in duty.", "임무 중 비전투 상태에서 이동 속도 증가 기술 사용");
		Add("Use movement speed increase abilities when out of combat and out of duty.", "임무 밖 비전투 상태에서 이동 속도 증가 기술 사용");
		Add("Use Sprint when a party tank is sprinting (non-tanks only).", "파티 탱커가 전력 질주하면 함께 전력 질주(탱커 외)");
		Add("Use beneficial ground-targeted actions", "이로운 지면 지정 기술 사용");
		Add("Use beneficial ground-targeted actions when moving.", "이동 중에도 이로운 지면 지정 기술 사용");
		Add("Use beneficial ground-targeted actions only on self, skipping other logic.", "이로운 지면 지정 기술을 다른 로직 없이 자기 위치에만 사용");
		Add("Use beneficial ground-targeted actions on party Tank if present, skipping other logic.", "파티 탱커가 있으면 다른 로직 없이 탱커 위치에 이로운 지면 지정 기술 사용");
		Add("Show Action Timeline Window", "행동 타임라인 창 표시");
		Add("Lock timeline", "타임라인 잠금");
		Add("Timeline size", "타임라인 크기");
		Add("Only show timeline in combat", "전투 중에만 타임라인 표시");
		Add("Only show timeline when RSR is active", "RSR이 켜져 있을 때만 타임라인 표시");
		Add("Show oGCD actions in timeline", "타임라인에 oGCD 표시");
		Add("Show auto-attacks in timeline", "타임라인에 자동 공격 표시");
		Add("Save timeline to JSON file after combat", "전투 후 타임라인을 JSON 파일로 저장");
		Add("Record AOE actions", "광역 기술 기록");
		Add("Auto turn off RSR when combat is over for more than:", "전투가 끝나고 이 시간이 지나면 RSR 자동 끄기:");
		Add("Enable RSR click counter in main menu", "메인 메뉴에 RSR 클릭 횟수 표시");
		Add("Hide all warnings", "모든 경고 숨기기");
		Add("Only heal self when not a Healer", "힐러가 아니면 자신만 회복");
		Add("Only use healing abilities as a non-healer if there are no living healers in the party.", "힐러가 아닐 때는 파티에 살아 있는 힐러가 없을 때만 회복 기술 사용");
		Add("Show toggled setting and new value in chat.", "바꾼 설정과 새 값을 채팅창에 표시");
		Add("Record knockback actions", "넉백 기술 기록");
		Add("Set Blue Mage Actions Automatically", "청마도사 기술 자동 설정");
		Add("Auto turn off RSR when combat is over for more than...", "전투가 끝나고 이 시간이 지나면 RSR 자동 끄기...");
		Add("The angle of your vision cone", "시야각");
		Add("Melee Ranged action usage offset", "근접 원거리 기술 사용 거리 보정");
		Add("When their minimum HP is lower than this.", "최소 HP가 이 값보다 낮을 때");
		Add("Heal tank first if their HP is lower than this.", "탱커 HP가 이 값보다 낮으면 탱커 먼저 회복");
		Add("Heal healer first if their HP is lower than this.", "힐러 HP가 이 값보다 낮으면 힐러 먼저 회복");
		Add("Heal self first if your HP is lower than this.", "내 HP가 이 값보다 낮으면 나부터 회복");
		Add("Prioritize raising dead players over Healing/Defense.", "회복/방어보다 사망자 부활 우선");
		Add("Raise player by using Swiftcast/Dualcast if available", "가능하면 신속한 마법/연속 마법으로 부활");
		Add("Hard cast Raise logic", "일반 시전 부활 로직");
		Add("Raise styles", "부활 방식");
		Add("Raise players that have the Brink of Death debuff", "빈사 디버프가 있는 플레이어도 부활");
		Add("Raise non-Healers from bottom of party list to the top (Light Party 2 Healer Behavior)", "힐러가 아닌 사망자는 파티 목록 아래부터 부활(4인 파티 2힐러 방식)");
		Add("Raise Red Mage and Summoners first if no Tanks or Healers are dead", "탱커·힐러 사망자가 없으면 적마도사·소환사 먼저 부활");
		Add("How early before next GCD should RSR use swiftcast for raise", "부활용 신속한 마법을 다음 GCD 몇 초 전에 쓸지");
		Add("Random delay range for resurrecting players.", "부활 무작위 지연 범위");
		Add("Random delay range for dispelling statuses.", "디스펠 무작위 지연 범위");
		Add("Never raise player if MP is less than this", "MP가 이 값보다 적으면 부활하지 않음");
		Add("HP standard deviation for using AoE heal.", "광역 회복을 쓸 HP 표준편차");
		Add("Heal party members when not in combat.", "비전투 상태에서도 파티원 회복");
		Add("Heal solo instance NPCs (Only enable as needed)", "솔로 인스턴스 NPC 회복(필요할 때만)");
		Add("Heal and raise Party NPCs.", "파티 NPC 회복·부활");
		Add("Treat your chocobo as a party member", "내 초코보를 파티원으로 취급");
		Add("Treat focus targeted player as party member in alliance raids", "얼라이언스 레이드에서 주시 대상 플레이어를 파티원으로 취급");
		Add("Heal party members with GCD if there is nothing to do in combat.", "전투 중 할 일이 없으면 GCD로 파티원 회복");
		Add("Prioritize Low HP tank for tankbusters.", "탱커버스터 때 HP 낮은 탱커 우선");
		Add("The duration of special windows opened by /rotation commands by default.", "/rotation 명령으로 여는 특수 상태의 기본 지속 시간");
		Add("Random range of delay for RSR to stop attacking when the target is dead or immune to damage.", "대상이 죽거나 무적일 때 공격을 멈추기까지의 무작위 지연 범위");
		Add("The range of random delay before interrupting hostile targets.", "적 시전 방해 전 무작위 지연 범위");
		Add("Provoke random delay range.", "도발 무작위 지연 범위");
		Add("Not In Combat random delay range.", "비전투 상태 무작위 지연 범위");
		Add("Clicking actions random delay range.", "기술 클릭 무작위 지연 범위");
		Add("Downtime healing delay range.", "다운타임 회복 지연 범위");
		Add("How soon before countdown is finished to start casting or attacking.", "카운트다운 종료 몇 초 전에 시전·공격을 시작할지");
		Add("Next action size", "다음 행동 크기");
		Add("Special button size", "특수 버튼 크기");
		Add("Control Progress Height", "조작 창 진행 막대 높이");
		Add("Stop healing when time to kill is lower than:", "예상 처치 시간이 이 값보다 짧으면 회복 중지:");
		Add("The minimum time between updating RSR information. (Raising this will help with framerate issues but can cause issues with rotation performance)", "RSR 정보 갱신 최소 간격(올리면 프레임에는 도움이 되지만 로테이션 성능이 떨어질 수 있음)");
		Add("Action Ahead (Percent of your GCD time remaining on a GCD cycle before RSR will try to queue the next GCD)", "선입력 시점(남은 GCD 시간의 몇 %에서 다음 GCD를 대기열에 넣을지)");
		Add("Remove extra lag-induced animation lock delay from instant casts (read tooltip!)", "즉시 시전의 지연으로 생긴 추가 애니메이션 잠금 제거(도움말을 꼭 읽으세요!)");
		Add("Animation lock max. simulated delay (read tooltip!)", "애니메이션 잠금 최대 모의 지연(도움말을 꼭 읽으세요!)");
		Add("Animation lock delay smoothing factor", "애니메이션 잠금 지연 평활 계수");
		Add("Remove extra framerate-induced cooldown delay", "프레임 때문에 생기는 추가 재사용 지연 제거");
		Add("Max cooldown adjustment (ms)", "최대 재사용 보정(ms)");
		Add("Enable cactbot timeline integration (Extremely experimental)", "cactbot 타임라인 연동 켜기(매우 실험적)");
		Add("Show cactbot event toasts (debug)", "cactbot 이벤트 알림 표시(디버그)");
		Add("Highlight color.", "강조 색");
		Add("Target color", "대상 색");
		Add("Locked Control Window's Background", "잠긴 조작 창 배경");
		Add("Unlocked Control Window's Background", "잠기지 않은 조작 창 배경");
		Add("Info Window's Background", "정보 창 배경");
		Add("Use movement actions towards the object/mob in the center of the screen", "화면 중앙의 오브젝트/몬스터를 향해 이동 기술 사용");
		Add("Prioritize mob/object targets with attack markers", "공격 표식이 있는 몬스터/오브젝트 우선");
		Add("Prioritize enemy parts", "적의 부위 우선");
		Add("Never attack targets with stop markers.", "정지 표식이 있는 대상은 공격하지 않음");
		Add("Treat 1hp targets as invincible.", "HP 1인 대상을 무적으로 취급");
		Add("Ignore Non-Fate targets while in a Fate and Fate targets if not in Fate.", "FATE 중에는 FATE 외 대상을, FATE 밖에서는 FATE 대상을 무시");
		Add("Move to the furthest position for targeting area movement actions.", "범위 이동 기술은 가장 먼 위치로 이동");
		Add("Hard Target for all actions", "모든 기술에 직접 대상 지정");
		Add("Set target to closest targetable enemy if no valid action target nearby and target not set while in combat (This works in Manual mode as well)", "전투 중 대상이 없고 근처에 유효한 기술 대상이 없으면 가장 가까운 적을 대상으로(수동 모드에서도 동작)");
		Add("Only attack targets in view.", "시야에 보이는 대상만 공격");
		Add("Only attack targets in vision cone", "시야각 안의 대상만 공격");
		Add("Target Hunt/Relic/Leve priority. (Relic behavior bugged)", "마물/유물/길드 의뢰 대상 우선(유물 동작은 버그 있음)");
		Add("Target quest priority (Overrides engage setting).", "퀘스트 대상 우선(교전 설정보다 우선)");
		Add("Block targeting quest mobs belonging to other players.", "다른 플레이어의 퀘스트 몬스터는 대상으로 삼지 않음");
		Add("Ignore all other FATE target when Forlorn available.", "Forlorn이 있으면 다른 FATE 대상은 모두 무시");
		Add("Ignore target dummies", "허수아비 무시");
		Add("Target Fate priority", "FATE 대상 우선");
		Add("Delay autotarget.", "자동 대상 지정 지연");
		Add("Range of time before locking onto aggro'd or new target to attack", "어그로가 끌리거나 새 대상이 생겼을 때 공격 대상으로 고정하기까지의 시간 범위");
		Add("The size of the sector angle that can be selected as the moveable target", "이동 대상으로 고를 수 있는 부채꼴 각도");
		Add("Treat target dummy as a boss.", "허수아비를 보스로 취급");
		Add("If target's TTK is higher than this, regard it as boss.", "예상 처치 시간이 이 값보다 길면 보스로 간주");
		Add("If target's TTK is lower than this, regard it as dying.", "예상 처치 시간이 이 값보다 짧으면 죽어 가는 것으로 간주");
		Add("If target's HP percentage is lower than this, regard it as dying.", "HP 비율이 이 값보다 낮으면 죽어 가는 것으로 간주");
		Add("Prioritize Low HP targets instead of High HP targets when using Small Target and multiple Small targets present.", "작은 대상 모드에서 작은 대상이 여럿이면 HP 높은 쪽 대신 낮은 쪽 우선");
		Add("Prioritize Low HP targets instead of High HP targets when using Big Target and multiple Big targets present.", "큰 대상 모드에서 큰 대상이 여럿이면 HP 높은 쪽 대신 낮은 쪽 우선");
		Add("/rotation Cycle behaviour", "/rotation Cycle 동작");
		Add("Engage settings", "교전 설정");
		Add("The modifier key to unlock the movement temporarily", "이동 잠금을 잠시 푸는 보조 키");
		Add("Random range of simulated presses per action", "기술당 모의 입력 횟수의 무작위 범위");
		Add("MP threshold under which to use Lucid Dreaming", "자각몽을 쓸 MP 기준값");
		Add("The HP%% for tank to use invulnerability", "탱커가 무적기를 쓸 HP%%");
	}

	private static void AddConfigDescriptions()
	{
		Add("Treat OmegaM/OmegaF as immune if you have their corresponding Packet Filter status (also applies to Normal).", "해당 패킷 필터 상태가 있으면 오메가M/오메가F를 면역으로 취급(일반 난이도에도 적용).");
		Add("Treat Wolf of Wind/Wolf of Stone as immune if you don't have the corresponding status for it.", "대응하는 상태가 없으면 바람 늑대/돌 늑대를 면역으로 취급.");
		Add("This should clear up any targeting issues when a nail, the boss, and a flail are near each other at the same time.", "못·보스·도리깨가 동시에 가까이 있을 때의 대상 지정 문제를 줄입니다.");
		Add("Treat Cells as immune if you don't have the corresponding status for it.", "대응하는 상태가 없으면 세포를 면역으로 취급.");
		Add("Prioritize Doornail or Flail based on role and distance to target.", "역할과 거리에 따라 못 또는 도리깨를 우선 대상으로.");
		Add("Priotize Red Hot if you have firesnaking buff, and Deep Blue if you have watersnaking buff (also applies to Normal).", "불뱀 버프가 있으면 Red Hot을, 물뱀 버프가 있으면 Deep Blue를 우선(일반 난이도에도 적용).");
		Add("Treat Bismark Shell/Bismark Corona as immune if you don't have the Whaleback status", "고래등 상태가 없으면 비스마르크 껍질/코로나를 면역으로 취급");
		Add("Treat Pall of Rage/Pall of Grief as immune if you don't have the corresponding status for it.", "대응하는 상태가 없으면 분노의 장막/비탄의 장막을 면역으로 취급.");
		Add("Treat Shadow as immune if you don't have the corresponding status", "대응하는 상태가 없으면 그림자를 면역으로 취급");
		Add("Treat Jagd Doll ads as immune when HP is less than 25%.", "야크트 돌 쫄의 HP가 25% 미만이면 면역으로 취급.");
		Add("Treat True Heart ad as immune.", "진심 쫄을 면역으로 취급.");
		Add("Treat OmegaM/OmegaF as immune if you have their corresponding Packet Filter status.", "해당 패킷 필터 상태가 있으면 오메가M/오메가F를 면역으로 취급.");
		Add("Treat Crystal Of Darkness ad as immune.", "어둠의 크리스탈 쫄을 면역으로 취급.");
		Add("Treat bosses as immune if you don't have the corresponding status for it.", "대응하는 상태가 없으면 보스를 면역으로 취급.");
		Add("Treat Colossus Rubricatus as immune while its casting scripted action which leads to its death.", "콜로서스 루브리카투스가 죽음으로 이어지는 연출 기술을 시전하는 동안 면역으로 취급.");
		Add("Treat Liars Lyre as immune if you don't have the Unfooled status.", "Unfooled 상태가 없으면 거짓말쟁이의 수금을 면역으로 취급.");
		Add("Treat Jailers in second boss fight as immune if you don't have corresponding buff.", "2보스전에서 대응하는 버프가 없으면 간수를 면역으로 취급.");
		Add("Treat Triton/Nereid/Phobos as immune if you don't have the corresponding status for it.", "대응하는 상태가 없으면 트리톤/네레이드/포보스를 면역으로 취급.");
		Add("Treat the first boss of Forked Tower as immune if you don't have the corresponding status for it.", "대응하는 상태가 없으면 갈림탑 1보스를 면역으로 취급.");
		Add("Treat Tiny Mage CE mobs as immune if you're more than 5 yalms away and they are not the farthest along their cast.", "5야드 이상 떨어져 있고 시전이 가장 많이 진행된 개체가 아니면 꼬마 마도사 CE 몬스터를 면역으로 취급.");
		Add("Enable tracking of elemental weaknesses for debug. This enables you to track weaknesses to report to dev. See Debug > Occult Crescent Weaknesses.", "디버그용 속성 약점 추적을 켭니다. 개발자에게 보고할 약점을 기록할 수 있습니다. 디버그 > Occult Crescent 약점 참조.");
		Add("Treat Eminent Grief as immune if you don't have Light Vengeance buff, and treat Devoured Eater as immune if you don't have Dark Vengeance buff.", "빛의 복수 버프가 없으면 Eminent Grief를, 어둠의 복수 버프가 없으면 Devoured Eater를 면역으로 취급.");
		Add("Treat Thanatos as immune if you don't have Astral Realignment buff.", "Astral Realignment 버프가 없으면 타나토스를 면역으로 취급.");
		Add("Treat Irminsul and Sawtooth as immune if you don't have corresponding buff.", "대응하는 버프가 없으면 이르민술과 톱니를 면역으로 취급.");
		Add("Treat each Superior Flight Unit as immune if you don't have corresponding buff.", "대응하는 버프가 없으면 각 상위 비행 유닛을 면역으로 취급.");
		Add("Treat each Hansel/Gretel as immune if you are at an angle that would cause you to take rebound damage from the shield mechanic.", "방패 기믹의 반사 피해를 받을 각도에 있으면 해당 헨젤/그레텔을 면역으로 취급.");
		Add("Treat each Ark Angel as immune if you don't have corresponding buff.", "대응하는 버프가 없으면 각 방주의 천사를 면역으로 취급.");
		Add("Treat Alexander and/or Gordius Systems as immune if they have Perfect Defense.", "완전 방어 상태인 알렉산더/고르디우스 시스템을 면역으로 취급.");
		Add("Treat Cloud of Darkness/Stygian as immune if you don't have corresponding buff.", "대응하는 버프가 없으면 어둠의 구름/스티기안을 면역으로 취급.");
		Add("Custom logic to treat certain drakes as immune to kill them in a specific order for the purposes Variant path 12.", "변형 던전 12번 경로를 위해 특정 드레이크를 정해진 순서로 잡도록 면역 처리하는 로직.");
		Add("Priotizes limited time mobs in treasure dungeons to resolve extra loot mechanic.", "보물 던전에서 추가 보상 기믹을 위해 시간제한 몬스터를 우선.");
		Add("Sets mobs with number plates as top priority in order from lowest to highest to resolve extra loot mechanic.", "추가 보상 기믹을 위해 번호판 몬스터를 낮은 번호부터 최우선으로.");
		Add("When enabled and BossModReborn is loaded, RSR will allow actions planned in BMR's Cooldown Planner to pass through the intercept system when their window is active.", "켜져 있고 BossModReborn이 로드되어 있으면, BMR 쿨다운 플래너에 계획된 기술은 해당 시간대에 가로채기 시스템을 통과합니다.");
		Add("Full: Use all available AoE actions.\nCleave: Use only single-target AoE actions.\nOff: Do not use any AoE actions.", "전체: 쓸 수 있는 모든 광역 기술 사용.\n클리브: 단일 대상형 광역 기술만 사용.\n끄기: 광역 기술을 쓰지 않음.");
		Add("Never use any AoE action when this may attack mobs that are not hostile targets.", "적 대상이 아닌 몬스터를 건드릴 수 있으면 광역 기술을 절대 쓰지 않음.");
		Add("Automatically turn off combat state when moving between different areas.", "지역을 이동할 때 전투 상태를 자동으로 끕니다.");
		Add("Automatically turn off combat state during cutscenes.", "컷신 중 전투 상태를 자동으로 끕니다.");
		Add("Automatically turn off combat state when you change your job/class.", "직업/클래스를 바꾸면 전투 상태를 자동으로 끕니다.");
		Add("Automatically turn off combat state when your character dies.", "캐릭터가 죽으면 전투 상태를 자동으로 끕니다.");
		Add("Automatically turn off combat state when a duty (instance) ends.", "임무(인스턴스)가 끝나면 전투 상태를 자동으로 끕니다.");
		Add("Show a popup window with the changelog when the plugin updates.", "플러그인이 업데이트되면 변경 사항 창을 띄웁니다.");
		Add("Display the plugin's current status in the server information bar.", "서버 정보 표시줄에 플러그인의 현재 상태를 표시합니다.");
		Add("Show a toast notification with the combat state when changed.", "전투 상태가 바뀌면 알림(토스트)을 표시합니다.");
		Add("Prevents your character from moving while casting or using specific actions.", "시전 중이거나 특정 기술을 쓰는 동안 캐릭터가 움직이지 않게 합니다.");
		Add("This setting is only used if the rotation specifically supports automatic tincture usage.", "로테이션이 영약 자동 사용을 지원할 때만 쓰이는 설정입니다.");
		Add("Enable to automatically use anti-knockback abilities when needed based on anti-knockback action list in List menu.", "켜면 목록 메뉴의 넉백 방지 기술 목록을 기준으로 필요할 때 넉백 방지 기술을 자동 사용합니다.");
		Add("Enable to allow the plugin to use HP potions automatically.", "켜면 플러그인이 HP 물약을 자동으로 사용합니다.");
		Add("Enable to allow the plugin to use MP potions automatically.", "켜면 플러그인이 MP 물약을 자동으로 사용합니다.");
		Add("Enable to allow the plugin to use Phoenix Down item. (Experimental feature)", "켜면 플러그인이 불사조의 꼬리를 사용합니다(실험적 기능).");
		Add("Enable to allow AoE actions to hit targets with priority markers.", "켜면 우선 표식이 있는 대상에게도 광역 기술이 들어갑니다.");
		Add("When teaching mode is active, automatically switch your target to match the rotation's suggested action target. Useful for tanks and healers where the optimal target may differ from your current selection.", "교습 모드에서 로테이션이 제안한 기술의 대상으로 내 대상을 자동으로 바꿉니다. 최적 대상이 현재 선택과 다를 수 있는 탱커·힐러에게 유용합니다.");
		Add("When teaching mode is active, display the rotation's suggested target name below the Next Action icon. Shown in orange if you don't have that target selected, green if you do.", "교습 모드에서 다음 행동 아이콘 아래에 로테이션이 제안한 대상 이름을 표시합니다. 그 대상을 선택하지 않았으면 주황색, 선택했으면 초록색입니다.");
		Add("A small Auto / Manual / Off switch for the autorotation state. /rotation Control shows and hides it too.", "자동 로테이션 상태용 작은 자동/수동/끄기 스위치입니다. /rotation Control 명령으로도 표시·숨김할 수 있습니다.");
		Add("The Heal, Defense, Movement and Rotation buttons on the Control window. The button at the top right of the window shows and hides them too.", "조작 창의 회복·방어·이동·로테이션 버튼입니다. 창 오른쪽 위 버튼으로도 표시·숨김할 수 있습니다.");
		Add("Show the keybind of the hotbar slot that holds the next action. Only visible hotbars are checked.", "다음 행동이 들어 있는 핫바 칸의 단축키를 표시합니다. 보이는 핫바만 확인합니다.");
		Add("Scales the whole Next Action window: the action icon, the GCD bar, the keybind and the target hint.", "다음 행동 창 전체(기술 아이콘, GCD 막대, 단축키, 대상 힌트)의 크기를 조절합니다.");
		Add("Displays rotating tips in the main panel; updates every 7 seconds.", "메인 패널에 팁을 돌아가며 표시합니다. 7초마다 바뀝니다.");
		Add("When enabled, actions you have disabled in RSR will be tinted on in-game hotbars.", "켜면 RSR에서 해제한 기술이 게임 핫바에서 색이 입혀져 보입니다.");
		Add("Prints each setting's description underneath its name instead of only in the hover tooltip. Turn this off for a denser list.", "설정 설명을 도움말에만 두지 않고 이름 아래에도 표시합니다. 목록을 촘촘하게 보려면 끄세요.");
		Add("This acts as the primary color that all other colors are derived from.", "다른 모든 색이 파생되는 기본 색입니다.");
		Add("Scales the text in every RSR window, on top of Dalamud's own font settings.", "Dalamud 글꼴 설정에 더해 모든 RSR 창의 글자 크기를 조절합니다.");
		Add("Scales the padding, spacing and controls in every RSR window. Turn it down for a more compact layout; text keeps to the Text size setting.", "모든 RSR 창의 여백·간격·컨트롤 크기를 조절합니다. 줄이면 더 촘촘해지며 글자는 글자 크기 설정을 따릅니다.");
		Add("Scales the space around and between things in every RSR window: window edges, card and row padding, and the gaps between items. Buttons, icons and text keep their size.", "모든 RSR 창에서 요소 주변과 사이의 공간(창 가장자리, 카드·행 여백, 항목 간격)을 조절합니다. 버튼·아이콘·글자 크기는 그대로입니다.");
		Add("If you have another healer on the team, their healing might put the target player(s) above the healing threshold and you'll waste MP. This interrupts the cast if it happens.", "파티에 다른 힐러가 있으면 그 힐러의 회복으로 대상이 기준값을 넘어 MP를 낭비할 수 있습니다. 그럴 때 시전을 끊습니다.");
		Add("It is recommended to check this option if you are playing Raids or you can plan the heal and defense ability usage by yourself.", "레이드를 하거나 회복·방어 기술 사용을 직접 계획할 수 있다면 이 옵션을 켜는 것이 좋습니다.");
		Add("When enabled and BossModReborn is loaded, RSR will use its timeline data to trigger defensive abilities before raidwides and tankbusters hit.", "켜져 있고 BossModReborn이 로드되어 있으면, 타임라인 데이터로 광역기·탱커버스터가 들어오기 전에 방어 기술을 씁니다.");
		Add("Automatically use provoke when an enemy is attacking a non-tank member of the party while there is more than one tank in party.", "파티에 탱커가 둘 이상일 때 적이 탱커가 아닌 파티원을 공격하면 자동으로 도발합니다.");
		Add("A scrolling record of the actions you use: GCDs on the top lane with their cast and recast, oGCDs beneath them with their animation lock.", "사용한 기술의 흐름 기록입니다. 위 줄은 GCD(시전·재사용), 아래 줄은 oGCD(애니메이션 잠금)입니다.");
		Add("Stops the timeline from being moved or resized. Hover over it to unlock it again.", "타임라인을 옮기거나 크기를 바꾸지 못하게 합니다. 다시 풀려면 마우스를 올리세요.");
		Add("Scales the whole timeline: the icons, the lanes and how far a second stretches.", "타임라인 전체(아이콘, 줄, 1초의 길이)의 크기를 조절합니다.");
		Add("When using a Blue Mage Rotation, RSR can automatically set your spell book to the spells required by that rotation.", "청마도사 로테이션을 쓸 때 RSR이 그 로테이션에 필요한 마법으로 마법서를 자동 설정합니다.");
		Add("If this is disabled, you will never use Swiftcast/Dualcast to raise players.", "끄면 부활에 신속한 마법/연속 마법을 절대 쓰지 않습니다.");
		Add("Controls how much party members' HP must differ before using AoE healing instead of single-target heals. Lower values require party members to have more similar HP for AoE healing to trigger (more selective). Higher values allow AoE healing even when HP differences are larger (less selective). Adjust only if you want to fine-tune AoE heal behavior.", "단일 회복 대신 광역 회복을 쓰려면 파티원 HP가 얼마나 비슷해야 하는지 정합니다. 낮을수록 HP가 더 비슷해야 광역 회복이 나가고(더 까다로움), 높을수록 차이가 커도 나갑니다(덜 까다로움). 광역 회복 동작을 세밀하게 조정할 때만 바꾸세요.");
		Add("Experimental.", "실험적.");
		Add("Experimental, includes Chaotic.", "실험적. 카오틱 포함.");
		Add("Scales the Next action icons in the Control window, and the icon in the Intercepted Action window. At 100% the GCD icon is 40 pixels and the oGCD icon is 30 pixels.", "조작 창의 다음 행동 아이콘과 가로챈 행동 창의 아이콘 크기를 조절합니다. 100%에서 GCD 아이콘은 40px, oGCD 아이콘은 30px입니다.");
		Add("Scales the Control window's special buttons (Heal AoE, Forward, Dispel and the rest): their icons, labels and padding together. At 100% the GCD icon is 40 pixels and the oGCD icon is 30 pixels.", "조작 창의 특수 버튼(광역 회복, 전진, 디스펠 등)의 아이콘·글자·여백을 함께 조절합니다. 100%에서 GCD 아이콘은 40px, oGCD 아이콘은 30px입니다.");
		Add("This setting controls how many oGCDs RSR will try to fit in a single GCD window\nLower numbers mean more oGCDs, but potentially more GCD clipping", "한 GCD 사이에 RSR이 oGCD를 몇 개 넣으려 할지 정합니다\n낮을수록 oGCD가 많이 들어가지만 GCD가 밀릴 수 있습니다");
		Add("Do NOT use with XivAlexander, BMR tweaks enabled, or NoClippy - this should automatically disable itself if they are detected, but double check first!", "XivAlexander, BMR 트윅, NoClippy와 함께 쓰지 마세요. 감지되면 스스로 꺼지지만 먼저 직접 확인하세요!");
		Add("Configures the maximum simulated delay in milliseconds when using animation lock removal - this is required and cannot be reduced to zero. Setting this to 20ms will enable triple-weaving when using autorotation. The minimum setting to remove triple-weaving is 26ms. The minimum of 20ms has been accepted by FFLogs and should not cause issues with your logs.", "애니메이션 잠금 제거 시 모의 지연의 최대값(ms)입니다. 필수 값이며 0으로 줄일 수 없습니다. 20ms로 두면 자동 로테이션에서 트리플 위빙이 됩니다. 트리플 위빙을 막는 최소값은 26ms입니다. 최소값 20ms는 FFLogs가 허용하므로 로그에 문제가 생기지 않습니다.");
		Add("Dynamically adjusts cooldown and animation locks to ensure queued actions resolve immediately regardless of framerate limitations", "프레임 제한과 관계없이 대기열의 기술이 바로 나가도록 재사용·애니메이션 잠금을 동적으로 보정합니다");
		Add("Connects to OverlayPlugin's WebSocket server and reacts to cactbot broadcast messages (raidwide, tankbuster, knockback, downtime/untargetable).", "OverlayPlugin의 WebSocket 서버에 연결해 cactbot 방송 메시지(광역기, 탱커버스터, 넉백, 다운타임/대상 불가)에 반응합니다.");
		Add("Show a toast when a cactbot broadcast is received and mapped to a RotationSolver special.", "cactbot 방송을 받아 RotationSolver 특수 상태로 연결하면 알림을 표시합니다.");
		Add("If enabled, movement actions target the object or mob at the center of your screen. If disabled, they target the object or mob your character is facing.", "켜면 이동 기술이 화면 중앙의 오브젝트/몬스터를 향합니다. 끄면 캐릭터가 바라보는 오브젝트/몬스터를 향합니다.");
		Add("Targets with attack markers will be prioritized for actions.", "공격 표식이 있는 대상을 기술 대상으로 우선합니다.");
		Add("Enemy parts, such as Titan's Heart, will be prioritized as targets.", "타이탄의 심장 같은 적의 부위를 대상으로 우선합니다.");
		Add("Targets with stop markers will not be attacked.", "정지 표식이 있는 대상은 공격하지 않습니다.");
		Add("Targets with only 1 HP will be treated as invincible and ignored; for rare cases where target is invincible but is not given a status for it.", "HP가 1인 대상을 무적으로 취급해 무시합니다. 무적인데 상태 효과가 없는 드문 경우를 위한 설정입니다.");
		Add("When in a Fate, only Fate targets are considered. When not in a Fate, Fate targets are ignored.", "FATE 중에는 FATE 대상만 고려하고, FATE 밖에서는 FATE 대상을 무시합니다.");
		Add("If this is disabled, RSR will only use the game's built-in soft-targeting for allies for heals, shields, etc.", "끄면 회복·보호막 등 아군 대상 기술에 게임 기본 소프트 타겟만 씁니다.");
		Add("(Do not set too low, can rip newly aggro'd dungeon mobs off tanks).", "(너무 낮게 두지 마세요. 던전에서 갓 어그로가 끌린 몬스터를 탱커에게서 빼앗을 수 있습니다.)");
		Add("If the selection mode is based on character facing, i.e., targets within the character's viewpoint are moveable targets.\nIf the selection mode is screen-centered, i.e., targets within a sector drawn upward from the character's point are movable targets.", "캐릭터 방향 기준이면 캐릭터 시점 안의 대상이 이동 대상입니다.\n화면 중앙 기준이면 캐릭터 위치에서 위쪽으로 그린 부채꼴 안의 대상이 이동 대상입니다.");
		Add("1.    Self-Target Fallback:\r\nIf range is zero, always targets the player and returns all affectable targets at the player's position.\r\n2.    Preferred Positions (OnLocations):\r\n•    Tries to get predefined beneficial positions for the current territory.\r\n•    If none are found and the content is a trial or raid, uses fallback points (e.g., 0,0 or 100,100 point as those are the center of arenas most of the time).\r\n•    Picks the closest point to the player, applies a small random offset, and checks if it’s within effect range.\r\n•    If so, returns that as the target area.\r\n3.    Boss Positional Fallback:\r\n•    If the current target is a boss with positional requirements and within range, uses the boss’s position (or a point within range) as the target area.\r\n4.    Party Member Fallback:\r\n•    Gathers party members within range + effect range.\r\n•    Attempts to find a party member who is being attacked (tank or focus target).\r\n•    If found, calculates whether to stay at the player’s position or move closer to the tank, based on distances and effect range.\r\n•    If not found or not needed, defaults to the player’s position.", "1.    자기 위치 대체:\r\n범위가 0이면 항상 플레이어를 대상으로 하고 플레이어 위치에서 영향받는 대상을 모두 반환합니다.\r\n2.    선호 위치(OnLocations):\r\n•    현재 지역에 미리 정한 이로운 위치가 있는지 찾습니다.\r\n•    없고 콘텐츠가 토벌전·레이드이면 대체 지점(대개 경기장 중앙인 0,0 또는 100,100)을 씁니다.\r\n•    플레이어와 가장 가까운 지점을 골라 작은 무작위 오프셋을 더한 뒤 효과 범위 안인지 확인합니다.\r\n•    범위 안이면 그 지점을 대상 지역으로 반환합니다.\r\n3.    보스 방향 공격 대체:\r\n•    현재 대상이 방향 공격이 있는 보스이고 사거리 안이면 보스 위치(또는 사거리 안의 지점)를 대상 지역으로 씁니다.\r\n4.    파티원 대체:\r\n•    사거리 + 효과 범위 안의 파티원을 모읍니다.\r\n•    공격받는 파티원(탱커 또는 주시 대상)을 찾습니다.\r\n•    찾으면 거리와 효과 범위를 보고 플레이어 위치에 둘지 탱커 쪽으로 옮길지 계산합니다.\r\n•    못 찾거나 필요 없으면 플레이어 위치를 씁니다.");
		Add("When enabled, non-healer jobs (such as DPS or tanks) will only use healing abilities if there are no healers in the party, or if all healers are incapacitated (at 0 HP). \r\nIf at least one healer is alive, non-healers will not use healing abilities.", "켜면 힐러가 아닌 직업(딜러·탱커)은 파티에 힐러가 없거나 힐러가 모두 쓰러졌을 때(HP 0)만 회복 기술을 씁니다. \r\n힐러가 한 명이라도 살아 있으면 회복 기술을 쓰지 않습니다.");
		Add("RB is for gamepad player.", "RB는 게임패드 사용자용입니다.");
	}
}
