// <auto-generated> by .github/himechan/cactbot-tankbusters.ps1 - do not edit by hand.
// Source: OverlayPlugin/cactbot e79ea7f16 2026-10-08, ui/raidboss/data (Apache-2.0). 436 cast ids.
namespace RotationSolver.Himechan;

/// <summary>Enemy cast ids that cactbot announces as tankbusters (StartsUsing triggers). Used by the Aquaveil logic.</summary>
internal static class HimechanCactbotTankbusters
{
	internal const string Source = "cactbot e79ea7f16 2026-10-08";

	internal static readonly HashSet<uint> CastIds =
	[
		1458, // 0x5B2 02-arr/raid/t5.ts : T5 Death Sentence
		2293, // 0x8F5 02-arr/dungeon/the_stone_vigil_hard.ts : Stone Vigil Hard Rake
		2482, // 0x9B2 03-hw/map/the_aquapolis.ts : Aquapolis Polis Hornet Final Sting
		3658, // 0xE4A 03-hw/raid/a1s.ts : A1S Hypercompressed You; 03-hw/raid/a1s.ts : A1S Hypercompressed Other
		3962, // 0xF7A 03-hw/dungeon/fractal_continuum.ts : Fractal Rapid Sever
		4348, // 0x10FC 03-hw/dungeon/aetherochemical_research_facility.ts : Facility Dark Orb
		5255, // 0x1487 03-hw/trial/thordan-ex.ts : ThordanEX Heavenly Heel
		5479, // 0x1567 03-hw/trial/sephirot-ex.ts : SephirotEx Chesed Buster
		5675, // 0x162B 03-hw/raid/a8s.ts : A8S Perpetual Ray
		5900, // 0x170C 03-hw/raid/a8s.ts : A8S Final Punch
		5936, // 0x1730 03-hw/raid/a8n.ts : A8N Perpetual Ray
		5966, // 0x174E 03-hw/raid/a8n.ts : A8N Double Rocket Punch
		6596, // 0x19C4 03-hw/trial/sophia-ex.ts : SophiaEX Tank Buster
		6633, // 0x19E9 03-hw/raid/a12s.ts : A12S Punishing Heat
		6669, // 0x1A0D 03-hw/raid/a12s.ts : A12S Chastening Heat
		6815, // 0x1A9F 03-hw/raid/a10s.ts : A10S Gobrush Rushgob
		6863, // 0x1ACF 03-hw/raid/a10n.ts : A10N Gobrush Rushgob
		6884, // 0x1AE4 03-hw/raid/a12n.ts : A12N Punishing Heat
		7193, // 0x1C19 03-hw/alliance/dun_scaith.ts : Dun Scaith Camisado
		7232, // 0x1C40 03-hw/dungeon/sohm_al_hard.ts : Sohm Al Hard Deadly Thrust
		7240, // 0x1C48 03-hw/dungeon/sohm_al_hard.ts : Sohm Al Hard Deadly Thrust
		7277, // 0x1C6D 03-hw/trial/zurvan-ex.ts : ZurvanEX Tyrfing
		7346, // 0x1CB2 03-hw/dungeon/baelsars_wall.ts : Baelsar Magitek Claw
		7362, // 0x1CC2 03-hw/dungeon/baelsars_wall.ts : Baelsar Griffin Claw
		7974, // 0x1F26 04-sb/dungeon/castrum_abania.ts : CastrumAbania Inferno Ketu Slash
		8153, // 0x1FD9 04-sb/dungeon/temple_of_the_fist.ts : Temple Fourfold Shear
		8227, // 0x2023 04-sb/trial/susano.ts : Susano Stormsplitter
		8243, // 0x2033 04-sb/trial/susano-ex.ts : SusEx Stormsplitter
		8331, // 0x208B 04-sb/dungeon/castrum_abania.ts : CastrumAbania Inferno Ketu Slash
		8332, // 0x208C 04-sb/dungeon/castrum_abania.ts : CastrumAbania Inferno Ketu Slash
		8542, // 0x215E 04-sb/trial/lakshmi-ex.ts : LakshmiEx Pull of Light Tank; 04-sb/trial/lakshmi-ex.ts : LakshmiEx Pull of Light Unexpected
		8857, // 0x2299 05-shb/dungeon/dohn_mheg.ts : Dohn Mheg Candy Cane
		8939, // 0x22EB 04-sb/raid/o3s.ts : O3S Critical Hit
		9073, // 0x2371 04-sb/raid/o2s.ts : O2S Evilsphere
		9175, // 0x23D7 04-sb/raid/o1n.ts : O1N Twin Bolt
		9405, // 0x24BD 04-sb/raid/o4n.ts : O4N Standard Thunder
		9487, // 0x250F 04-sb/raid/o2n.ts : O2N Evilsphere
		9525, // 0x2535 04-sb/map/the_lost_canals_of_uznair.ts : Lost Canals of Uznair Canal Scorpion Flying Press
		9563, // 0x255B 04-sb/map/the_lost_canals_of_uznair.ts : Lost Canals of Uznair Canal Thunderbeast Sparkstorm
		9687, // 0x25D7 04-sb/alliance/royal_city_of_rabanastre.ts : Rab Hashmal Rock Cutter
		9773, // 0x262D 04-sb/alliance/royal_city_of_rabanastre.ts : Rab Argath Crippling Blow
		9803, // 0x264B 04-sb/trial/shinryu-ex.ts : ShinryuEx Tera Slash
		9825, // 0x2661 04-sb/dungeon/drowned_city_of_skalla.ts : Skalla Rusting Claw
		9897, // 0x26A9 04-sb/ultimate/unending_coil_ultimate.ts : UCU Death Sentence
		9910, // 0x26B6 04-sb/ultimate/unending_coil_ultimate.ts : UCU Nael Ravensbeak
		9941, // 0x26D5 04-sb/ultimate/unending_coil_ultimate.ts : UCU Bahamut Flatten
		10092, // 0x276C 04-sb/raid/o7n.ts : O7N Arm And Hammer
		10121, // 0x2789 04-sb/raid/o7s.ts : O7S Arm And Hammer
		10131, // 0x2793 04-sb/dungeon/fractal_continuum_hard.ts : Fractal Hard Aetheroplasm
		10202, // 0x27DA 04-sb/trial/byakko-ex.ts : ByakkoEx Heavenly Strike
		10281, // 0x2829 04-sb/raid/o6s.ts : O6S Demonic Shear
		10282, // 0x282A 04-sb/raid/o6n.ts : O6N Demonic Shear
		10399, // 0x289F 04-sb/eureka/eureka_anemos.ts : Eureka Pazuzu Camisado
		10403, // 0x28A3 04-sb/raid/o5n.ts : O5N Doom Strike
		10417, // 0x28B1 04-sb/raid/o5s.ts : O5S Doom Strike
		10542, // 0x292E 04-sb/raid/o8n.ts : O8N Hyper Drive
		10797, // 0x2A2D 04-sb/trial/byakko.ts : Byakko Heavenly Strike
		11156, // 0x2B94 04-sb/dungeon/swallows_compass.ts : Swallows Compass Tengu Might
		11174, // 0x2BA6 04-sb/dungeon/swallows_compass.ts : Swallows Compass Short End
		11195, // 0x2BBB 04-sb/trial/tsukuyomi-ex.ts : TsukuyomiEx Torment
		11235, // 0x2BE3 04-sb/trial/tsukuyomi.ts : Tsukuyomi Torment Unto Death
		11326, // 0x2C3E 04-sb/alliance/ridorana_lighthouse.ts : Ridorana Famfrit Tide Pode
		11354, // 0x2C5A 04-sb/alliance/ridorana_lighthouse.ts : Ridorana Construct Destroy
		11377, // 0x2C71 04-sb/alliance/ridorana_lighthouse.ts : Ridorana Construct Destroy
		11483, // 0x2CDB 04-sb/alliance/ridorana_lighthouse.ts : Ridorana Belias Fire
		11527, // 0x2D07 04-sb/dungeon/swallows_compass.ts : Swallows Compass Short End
		11598, // 0x2D4E 04-sb/alliance/ridorana_lighthouse.ts : Ridorana Yiazmat Rake Buster
		11634, // 0x2D72 04-sb/dungeon/the_burn.ts : The Burn Aetherochemical Coil
		11848, // 0x2E48 04-sb/dungeon/st_mocianne_hard.ts : St Mocianne Hard Vine Whip
		11954, // 0x2EB2 04-sb/trial/tsukuyomi-ex.ts : TsukuyomiEx Torment
		12586, // 0x312A 04-sb/dungeon/st_mocianne_hard.ts : St Mocianne Hard Stone II
		12597, // 0x3135 04-sb/dungeon/st_mocianne_hard.ts : St Mocianne Mudsling
		12623, // 0x314F 04-sb/raid/o9n.ts : O9N Chaotic Dispersion
		12656, // 0x3170 04-sb/raid/o9s.ts : O9S Chaotic Dispersion
		12691, // 0x3193 04-sb/dungeon/the_burn.ts : The Burn Crystal Needle
		12714, // 0x31AA 04-sb/raid/o10s.ts : O10S Tail End
		12741, // 0x31C5 04-sb/raid/o10n.ts : O10N Tail End
		12832, // 0x3220 04-sb/trial/suzaku.ts : Suzaku Cremate
		12849, // 0x3231 04-sb/trial/suzaku.ts : Suzaku Phantom Flurry
		12909, // 0x326D 04-sb/raid/o11s.ts : O11S Mustard Bomb
		12935, // 0x3287 04-sb/raid/o11n.ts : O11N Mustard Bomb
		13009, // 0x32D1 04-sb/trial/suzaku-ex.ts : SuzakuEx Cremate
		13071, // 0x330F 04-sb/raid/o12n.ts : O12N Solar Ray
		13072, // 0x3310 04-sb/raid/o12n.ts : O12N Solar Ray
		13089, // 0x3321 04-sb/raid/o12n.ts : O12N Optimized Blade Dance
		13090, // 0x3322 04-sb/raid/o12n.ts : O12N Optimized Blade Dance
		13131, // 0x334B 04-sb/raid/o12s.ts : O12S Optimized Blade Dance
		13132, // 0x334C 04-sb/raid/o12s.ts : O12S Optimized Blade Dance
		13136, // 0x3350 04-sb/raid/o12s.ts : O12S Solar Ray; 04-sb/raid/o12s.ts : O12S Solar Ray Not You
		13137, // 0x3351 04-sb/raid/o12s.ts : O12S Solar Ray; 04-sb/raid/o12s.ts : O12S Solar Ray Not You
		13311, // 0x33FF 04-sb/map/the_shifting_altars_of_uznair.ts : Shifting Altars of Uznair Altar Skatene Reckless Abandon
		13342, // 0x341E 04-sb/map/the_shifting_altars_of_uznair.ts : Shifting Altars of Uznair Altar Arachne Dark Spike
		13364, // 0x3434 04-sb/map/the_shifting_altars_of_uznair.ts : Shifting Altars of Uznair The Great Gold Whisker Triple Trident
		13367, // 0x3437 04-sb/map/the_shifting_altars_of_uznair.ts : Shifting Altars of Uznair Altar Mandragora Optical Intrusion
		13371, // 0x343B 04-sb/map/the_shifting_altars_of_uznair.ts : Shifting Altars of Uznair Altar Airavata Huff
		13385, // 0x3449 04-sb/map/the_shifting_altars_of_uznair.ts : Shifting Altars of Uznair The Older One Mystic Flash
		13401, // 0x3459 04-sb/dungeon/ghimlyt_dark.ts : Ghimlyt Dark Cermet Drill
		13438, // 0x347E 04-sb/map/the_shifting_altars_of_uznair.ts : Shifting Altars of Uznair Altar Kelpie Torpedo
		13444, // 0x3484 04-sb/map/the_shifting_altars_of_uznair.ts : Shifting Altars of Uznair Altar Apanda Deadly Hold
		13732, // 0x35A4 05-shb/dungeon/dohn_mheg.ts : Dohn Mheg Crippling Blow
		14121, // 0x3729 04-sb/dungeon/ghimlyt_dark.ts : Ghimlyt Dark Innocence
		14122, // 0x372A 04-sb/dungeon/ghimlyt_dark.ts : Ghimlyt Dark Delta Trance
		14137, // 0x3739 04-sb/alliance/orbonne_monastery.ts : Orbonne Mustadio Arm Shot
		14162, // 0x3752 04-sb/alliance/orbonne_monastery.ts : Orbonne Cid Crush Helm Healer
		14190, // 0x376E 04-sb/dungeon/ghimlyt_dark.ts : Ghimlyt Dark Jarring Blow
		14234, // 0x379A 04-sb/eureka/eureka_hydatos.ts : BA AV Tankbuster
		14333, // 0x37FD 04-sb/trial/seiryu.ts : Seiryu Infirm Soul
		14438, // 0x3866 04-sb/alliance/orbonne_monastery.ts : Orbonne Agrias Thunder Slash
		14459, // 0x387B 04-sb/eureka/eureka_hydatos.ts : BA Raiden Tankbuster
		14506, // 0x38AA 04-sb/alliance/orbonne_monastery.ts : Orbonne Ultima Redemption
		14644, // 0x3934 04-sb/eureka/eureka_hydatos.ts : BA Art Tankbuster
		14661, // 0x3945 04-sb/eureka/eureka_hydatos.ts : BA Owain Tankbuster
		15497, // 0x3C89 05-shb/dungeon/qitana_ravel.ts : Qitana Stonefist
		15505, // 0x3C91 05-shb/dungeon/qitana_ravel.ts : Qitana Ripper Fang
		15513, // 0x3C99 05-shb/dungeon/qitana_ravel.ts : Qitana Rend
		15589, // 0x3CE5 05-shb/dungeon/malikahs_well.ts : Malikah Stone Flail
		15595, // 0x3CEB 05-shb/dungeon/malikahs_well.ts : Malikah Efface
		15611, // 0x3CFB 05-shb/dungeon/mt_gulg.ts : Gulg Rake
		15625, // 0x3D09 05-shb/dungeon/mt_gulg.ts : Gulg Catechism
		15634, // 0x3D12 05-shb/dungeon/mt_gulg.ts : Gulg Sforzando
		15660, // 0x3D2C 05-shb/trial/titania-ex.ts : TitaniaEx Fae Light; 05-shb/trial/titania-ex.ts : TitaniaEx Fae Light Cleave
		15670, // 0x3D36 05-shb/trial/titania-ex.ts : TitaniaEx Hard Swipe
		15690, // 0x3D4A 05-shb/trial/titania-ex.ts : TitaniaEx Divination
		15707, // 0x3D5B 05-shb/trial/titania.ts : Titania Divination
		15717, // 0x3D65 05-shb/dungeon/twinning.ts : Twinning Augurium
		15752, // 0x3D88 05-shb/raid/e1s.ts : E1S Spear Of Paradise
		15777, // 0x3DA1 05-shb/raid/e1n.ts : E1N Spear Of Paradise
		15812, // 0x3DC4 05-shb/dungeon/holminster_switch.ts : Holminster Pillory
		15823, // 0x3DCF 05-shb/dungeon/holminster_switch.ts : Holminster Tickler
		15831, // 0x3DD7 05-shb/dungeon/holminster_switch.ts : Holminster Head Crusher
		15853, // 0x3DED 05-shb/dungeon/twinning.ts : Twinning Thunder Beam
		15867, // 0x3DFB 05-shb/dungeon/twinning.ts : Twinning Rail Cannon
		15876, // 0x3E04 05-shb/dungeon/akadaemia_anyder.ts : Anyder Puncture
		15907, // 0x3E23 05-shb/dungeon/akadaemia_anyder.ts : Anyder Shockbolt
		15949, // 0x3E4D 05-shb/raid/e2n.ts : E2N Shadowflame Tank; 05-shb/raid/e2n.ts : E2N Shadowflame Healer
		15969, // 0x3E61 05-shb/raid/e2s.ts : E2S Shadowflame Healer
		16035, // 0x3EA3 05-shb/trial/innocence.ts : Inno Righteous Bolt
		16073, // 0x3EC9 05-shb/trial/innocence-ex.ts : InnoEx Holy Sword Healer; 05-shb/trial/innocence-ex.ts : InnoEx Holy Sword Me
		16077, // 0x3ECD 05-shb/trial/innocence-ex.ts : InnoEx Righteous Bolt
		16633, // 0x40F9 05-shb/raid/e4n.ts : E4N Stonecrusher
		16662, // 0x4116 05-shb/raid/e4s.ts : E4S Stonecrusher
		16728, // 0x4158 05-shb/trial/hades.ts : Hades Ravenous Assault
		16737, // 0x4161 05-shb/trial/hades.ts : Hades Dual Strike Healer
		16964, // 0x4244 05-shb/hunts/lakeland.ts : Hunt Nuckelavee Torpedo
		17356, // 0x43CC 05-shb/hunts/the_tempest.ts : Hunt Gunitt The Deep Seeks
		17440, // 0x4420 05-shb/hunts/kholusia.ts : Hunt Pedantry Fevered Flagellation
		17488, // 0x4450 05-shb/hunts/kholusia.ts : Hunt Lil Murderer Goblin Punch
		17848, // 0x45B8 05-shb/hunts/the_raktika_greatwood.ts : Hunt Ixtab Tartarean Abyss
		17860, // 0x45C4 05-shb/hunts/the_raktika_greatwood.ts : Hunt Grassman Browbeat
		18026, // 0x466A 05-shb/hunts/amh_araeng.ts : Hunt Tarchia Wild Horn
		18203, // 0x471B 05-shb/dungeon/the_grand_cosmos.ts : Cosmos Storm of Color
		18276, // 0x4764 05-shb/dungeon/the_grand_cosmos.ts : Cosmos Captive Bolt
		18281, // 0x4769 05-shb/dungeon/the_grand_cosmos.ts : Cosmos Shadowbolt
		18342, // 0x47A6 05-shb/trial/hades-ex.ts : HadesEx Ravenous Assault
		18370, // 0x47C2 05-shb/trial/hades-ex.ts : HadesEx Fire IV; 05-shb/trial/hades-ex.ts : HadesEx Healers Blizzard/Fire IV
		18371, // 0x47C3 05-shb/trial/hades-ex.ts : HadesEx Blizzard IV; 05-shb/trial/hades-ex.ts : HadesEx Healers Blizzard/Fire IV
		18385, // 0x47D1 05-shb/trial/hades-ex.ts : HadesEx Height Of Chaos
		18422, // 0x47F6 05-shb/trial/hades-ex.ts : HadesEx Quadrastrike 2
		18577, // 0x4891 05-shb/ultimate/the_epic_of_alexander.ts : TEA Ordained Punishment
		18638, // 0x48CE 05-shb/alliance/the_copied_factory.ts : Copied Serial Clanging Blow
		18677, // 0x48F5 05-shb/alliance/the_copied_factory.ts : Copied 9S Neutralization
		19072, // 0x4A80 05-shb/ultimate/the_epic_of_alexander.ts : TEA Chastening Heat
		19135, // 0x4ABF 05-shb/trial/ruby_weapon.ts : Ruby Ruby Claw
		19143, // 0x4AC7 05-shb/trial/ruby_weapon.ts : Ruby Stamp
		19199, // 0x4AFF 05-shb/trial/ruby_weapon-ex.ts : RubyEx Ruby Claw
		19203, // 0x4B03 05-shb/trial/ruby_weapon-ex.ts : RubyEx Stamp
		19305, // 0x4B69 05-shb/dungeon/anamnesis_anyder.ts : AnAnyder Fetid Fang
		19314, // 0x4B72 05-shb/dungeon/anamnesis_anyder.ts : AnAnyder Fetid Fang
		19340, // 0x4B8C 05-shb/dungeon/anamnesis_anyder.ts : AnAnyder Bonebreaker
		19363, // 0x4BA3 05-shb/raid/e5n.ts : E5N Crippling Blow
		19402, // 0x4BCA 05-shb/raid/e5s.ts : E5S Crippling Blow
		19437, // 0x4BED 05-shb/raid/e6n.ts : E6N Instant Incineration
		19470, // 0x4C0E 05-shb/raid/e6s.ts : E6S Instant Incineration
		19696, // 0x4CF0 05-shb/trial/varis-ex.ts : VarisEx Citius
		19813, // 0x4D65 05-shb/raid/e8s.ts : E8S Double Slap
		19930, // 0x4DDA 05-shb/raid/e8n.ts : E8N Double Slap
		20234, // 0x4F0A 05-shb/trial/wol-ex.ts : WOLEx The Bitter End
		20264, // 0x4F28 05-shb/trial/wol.ts : WOL Bitter End
		20318, // 0x4F5E 05-shb/dungeon/heroes_gauntlet.ts : Heroes Gauntlet Twisted Touch
		20373, // 0x4F95 05-shb/eureka/bozjan_southern_front.ts : Bozja South Castrum Adrammelech Flare
		20421, // 0x4FC5 05-shb/alliance/the_puppets_bunker.ts : Puppet Superior Precision Guided Missile You; 05-shb/alliance/the_puppets_bunker.ts : Puppet Superior Precision Guided Missile Not You
		20427, // 0x4FCB 05-shb/dungeon/heroes_gauntlet.ts : Heroes Gauntlet Spectral Dream
		20588, // 0x506C 05-shb/eureka/bozjan_southern_front.ts : Bozja South Choctober Choco Slash
		20852, // 0x5174 05-shb/eureka/bozjan_southern_front.ts : Bozja South Castrum Lyon Twin Agonies
		20859, // 0x517B 05-shb/eureka/bozjan_southern_front.ts : Bozja South Castrum Dawon Scratch
		20957, // 0x51DD 05-shb/eureka/bozjan_southern_front.ts : Bozja South Castrum Brionac Electric Anvil
		20991, // 0x51FF 05-shb/eureka/bozjan_southern_front.ts : Bozja South Castrum Helldiver Magitek Missiles
		21011, // 0x5213 05-shb/alliance/the_puppets_bunker.ts : Puppet Light Maneuver Martial Arm Target; 05-shb/alliance/the_puppets_bunker.ts : Puppet Light Maneuver Martial Arm Healer
		21631, // 0x547F 05-shb/dungeon/matoyas_relict.ts : Matoyas Mudman Hard Rock
		21673, // 0x54A9 05-shb/map/the_shifting_oubliettes_of_lyhe_ghiah.ts : Shifting Oubliettes of Lyhe Ghiah Secret Korrigan Ram
		21703, // 0x54C7 05-shb/map/the_shifting_oubliettes_of_lyhe_ghiah.ts : Shifting Oubliettes of Lyhe Ghiah Secret Cladoselache Protolithic Puncture
		21710, // 0x54CE 05-shb/map/the_shifting_oubliettes_of_lyhe_ghiah.ts : Shifting Oubliettes of Lyhe Ghiah Secret Worm Brine Breath
		21716, // 0x54D4 05-shb/map/the_shifting_oubliettes_of_lyhe_ghiah.ts : Shifting Oubliettes of Lyhe Ghiah Secret Swallow Ceras
		21721, // 0x54D9 05-shb/map/the_shifting_oubliettes_of_lyhe_ghiah.ts : Shifting Oubliettes of Lyhe Ghiah Secret Basket Straight Punch
		21734, // 0x54E6 05-shb/map/the_shifting_oubliettes_of_lyhe_ghiah.ts : Shifting Oubliettes of Lyhe Ghiah Fuath Troublemaker Toy Hammer
		21757, // 0x54FD 05-shb/map/the_shifting_oubliettes_of_lyhe_ghiah.ts : Shifting Oubliettes of Lyhe Ghiah Daen Ose Sickle Strike
		21844, // 0x5554 05-shb/trial/emerald_weapon.ts : Emerald Emerald Shot
		21936, // 0x55B0 05-shb/trial/emerald_weapon-ex.ts : EmeraldEx Emerald Shot
		21995, // 0x55EB 05-shb/raid/e9n.ts : E9N Zero-Form Particle Beam
		22051, // 0x5623 05-shb/raid/e9s.ts : E9S Zero-Form Devouring Dark
		22094, // 0x564E 05-shb/raid/e11n.ts : E11N Powder Mark
		22178, // 0x56A2 05-shb/raid/e11s.ts : E11S Powder Mark
		22374, // 0x5766 05-shb/eureka/delubrum_reginae.ts : Delubrum Dahu Heat Breath
		22462, // 0x57BE 05-shb/eureka/delubrum_reginae_savage.ts : DelubrumSav Phantom Excruciation
		22487, // 0x57D7 05-shb/eureka/delubrum_reginae_savage.ts : DelubrumSav Lord Foe Splitter
		22523, // 0x57FB 05-shb/eureka/delubrum_reginae.ts : Delubrum Guard Rapid Sever Knight
		22537, // 0x5809 05-shb/eureka/delubrum_reginae.ts : Delubrum Guard Rapid Sever Soldier; 05-shb/eureka/delubrum_reginae.ts : Delubrum Phantom Excruciation
		22545, // 0x5811 05-shb/eureka/delubrum_reginae.ts : Delubrum Guard Shot In The Dark
		22643, // 0x5873 05-shb/raid/e12n.ts : E12N Formless Judgment
		22697, // 0x58A9 05-shb/raid/e12s.ts : E12S Promise Formless Judgment
		22727, // 0x58C7 05-shb/raid/e12s.ts : E12S Black Halo
		22801, // 0x5911 05-shb/dungeon/matoyas_relict.ts : Matoyas Porxie Minced Meat
		22862, // 0x594E 05-shb/eureka/delubrum_reginae_savage.ts : DelubrumSav Avowed Wrath Of Bozja
		22901, // 0x5975 05-shb/eureka/delubrum_reginae.ts : Delubrum Avowed Wrath Of Bozja
		22981, // 0x59C5 05-shb/eureka/delubrum_reginae.ts : Delubrum Queen Cleansing Slash
		23029, // 0x59F5 05-shb/eureka/delubrum_reginae_savage.ts : DelubrumSav Queen Cleansing Slash
		23253, // 0x5AD5 05-shb/eureka/delubrum_reginae_savage.ts : DelubrumSav Seeker Baleful Onslaught Buster
		23384, // 0x5B58 05-shb/dungeon/paglthan.ts : Paglthan Flatten
		23466, // 0x5BAA 05-shb/raid/e10s.ts : E10S Umbra Smash; 05-shb/raid/e10s.ts : E10S Umbra Smash Offtank Swap
		23470, // 0x5BAE 05-shb/eureka/zadnor.ts : Zadnor Blood Camisado
		23630, // 0x5C4E 05-shb/dungeon/paglthan.ts : Paglthan Critical Rip
		23698, // 0x5C92 05-shb/eureka/zadnor.ts : Zadnor Cuchulainn Might Of Malice
		23827, // 0x5D13 05-shb/eureka/zadnor.ts : Zadnor Face Rock Cutter
		23961, // 0x5D99 05-shb/eureka/zadnor.ts : Zadnor Time Fire
		24005, // 0x5DC5 05-shb/eureka/zadnor.ts : Zadnor Saunion High-Powered Magitek Ray
		24020, // 0x5DD4 05-shb/eureka/zadnor.ts : Zadnor Saunion Tooth and Talon
		24085, // 0x5E15 05-shb/eureka/zadnor.ts : Zadnor Diremite Crystal Needle
		24096, // 0x5E20 05-shb/eureka/zadnor.ts : Zadnor Grave Devour Soul
		24123, // 0x5E3B 05-shb/eureka/zadnor.ts : Zadnor Shadow Bladed Beak
		24208, // 0x5E90 05-shb/eureka/zadnor.ts : Zadnor Sartauvoir Burning Blade
		24509, // 0x5FBD 05-shb/trial/diamond_weapon-ex.ts : DiamondEx Auri Doomstead
		24536, // 0x5FD8 05-shb/trial/diamond_weapon.ts : Diamond Auri Doomstead
		25141, // 0x6235 06-ew/dungeon/vanaspati.ts : Vanaspati Terminus Snatcher Last Gasp
		25154, // 0x6242 06-ew/dungeon/vanaspati.ts : Vanaspati Terminus Wrecker Total Wreck
		25171, // 0x6253 06-ew/dungeon/vanaspati.ts : Vanaspati Svarbhanu Gnashing Of Teeth
		25182, // 0x625E 06-ew/dungeon/ktisis_hyperboreia.ts : Ktisis Lyssa Skull Dasher
		25257, // 0x62A9 06-ew/dungeon/the_tower_of_zot.ts : Zot Minduruva Bio; 06-ew/dungeon/the_tower_of_zot.ts : Zot Sanduruva Isitva Siddhi
		25280, // 0x62C0 06-ew/dungeon/the_tower_of_zot.ts : Zot Sanduruva Isitva Siddhi
		25290, // 0x62CA 06-ew/dungeon/the_tower_of_zot.ts : Zot Minduruva Bio
		25387, // 0x632B 06-ew/dungeon/stigma_dreamscape.ts : Dreamscape Mustard Bomb
		25525, // 0x63B5 06-ew/dungeon/stigma_dreamscape.ts : Dreamscape Wheel
		25543, // 0x63C7 06-ew/ultimate/dragonsongs_reprise_ultimate.ts : DSR Heavenly Heel
		25673, // 0x6449 06-ew/dungeon/the_aitiascope.ts : Aitiascope Livia Aglaea Bite
		25686, // 0x6456 06-ew/dungeon/the_aitiascope.ts : Aitiascope Rhitahtyn Anvil of Tartarus
		25700, // 0x6464 06-ew/dungeon/the_aitiascope.ts : Aitiascope Amon Dark Forte
		25743, // 0x648F 06-ew/dungeon/ktisis_hyperboreia.ts : Ktisis Ladon Lord Scratch
		25920, // 0x6540 06-ew/dungeon/the_dead_ends.ts : DeadEnds Pox Flail
		25949, // 0x655D 06-ew/dungeon/the_dead_ends.ts : DeadEnds Ra-La Pity
		25972, // 0x6574 06-ew/hunts/ultima_thule.ts : Hunt Chi Hellburner
		26099, // 0x65F3 06-ew/raid/p1n.ts : P1N Heavy Hand
		26153, // 0x6629 06-ew/raid/p1s.ts : P1S Heavy Hand
		26194, // 0x6652 06-ew/trial/endsinger.ts : Endsinger Hubris
		26290, // 0x66B2 06-ew/raid/p3n.ts : P3N Heat of Condemnation
		26434, // 0x6742 06-ew/dungeon/smileton.ts : Smileton Face Heart on Fire IV
		26436, // 0x6744 06-ew/dungeon/smileton.ts : Smileton Frameworker Steel Beam
		26449, // 0x6751 06-ew/dungeon/smileton.ts : Smileton The Big Cheese Piercing Missile
		26510, // 0x678E 06-ew/hunts/thavnair.ts : Hunt Daivadipa Drumbeat
		26638, // 0x680E 06-ew/raid/p2n.ts : P2N Doubled Impact
		26674, // 0x6832 06-ew/raid/p2s.ts : P2S Doubled Impact
		27078, // 0x69C6 06-ew/hunts/labyrinthos.ts : Hunt Hulder Storm of Color
		27144, // 0x6A08 06-ew/raid/p4s.ts : P4S Elegant Evisceration
		27179, // 0x6A2B 06-ew/raid/p4s.ts : P4S Heart Stake
		27216, // 0x6A50 06-ew/raid/p4n.ts : P4N Elegant Evisceration
		27223, // 0x6A57 06-ew/hunts/thavnair.ts : Hunt Sugriva Butcher
		27273, // 0x6A89 06-ew/hunts/ultima_thule.ts : Hunt Arch-Eta Steel Fang
		27323, // 0x6ABB 06-ew/hunts/mare_lamentorum.ts : Hunt Mousse Princess Banish
		27348, // 0x6AD4 06-ew/hunts/elpis.ts : Hunt Ophioneus Scratch
		27379, // 0x6AF3 06-ew/hunts/ultima_thule.ts : Hunt Fan Ail Death Sentence
		27490, // 0x6B62 06-ew/trial/zodiark.ts : Zodiark Ania
		27491, // 0x6B63 06-ew/trial/zodiark-ex.ts : ZodiarkEx Ania
		27617, // 0x6BE1 06-ew/hunts/thavnair.ts : Hunt Sphatika Gnaw
		27981, // 0x6D4D 06-ew/map/the_excitatron_6000.ts : Excitatron Heart on Fire IV
		28280, // 0x6E78 06-ew/raid/p4s.ts : P4S Demigod Double
		28447, // 0x6F1F 06-ew/dungeon/alzadaals_legacy.ts : Alzadaal Rail Cannon
		28530, // 0x6F72 06-ew/dungeon/alzadaals_legacy.ts : Alzadaal Crewel Slice
		28659, // 0x6FF3 02-arr/dungeon/brayfloxs_longstop.ts : Brayflox Normal Aiatar Salivous Snap
		28716, // 0x702C 06-ew/trial/endsinger-ex.ts : EndsingerEx Hubris
		28852, // 0x70B4 06-ew/alliance/aglaia.ts : Aglaia Rhalgr Destructive Bolt
		28906, // 0x70EA 06-ew/dungeon/the_sildihn_subterrane.ts : Sildihn Thorne Blistering Blow
		29571, // 0x7383 06-ew/trial/barbariccia-ex.ts : BarbaricciaEx Boulder Break
		29647, // 0x73CF 06-ew/trial/barbariccia.ts : Barbariccia Boulder Break Tankbuster
		29824, // 0x7480 06-ew/dungeon/the_fell_court_of_troia.ts : Troia Beatrice Hush
		29868, // 0x74AC 06-ew/dungeon/the_sildihn_subterrane.ts : Sildihn Shadowcaster Firesteel Fracture
		29869, // 0x74AD 06-ew/dungeon/another_sildihn_subterrane.ts : ASS Firesteel Fracture
		29903, // 0x74CF 06-ew/dungeon/the_sildihn_subterrane.ts : Sildihn Geryon Colossal Strike
		30065, // 0x7571 06-ew/trial/barbariccia-ex.ts : BarbaricciaEx Void Aero III
		30135, // 0x75B7 06-ew/trial/barbariccia.ts : Barbariccia Void Aero III
		30263, // 0x7637 06-ew/dungeon/the_fell_court_of_troia.ts : Troia Scarmiglione Firedamp
		30295, // 0x7657 06-ew/dungeon/the_sildihn_subterrane.ts : Sildihn Gladiator Mighty Smite
		30322, // 0x7672 06-ew/dungeon/another_sildihn_subterrane.ts : ASS Mighty Smite
		30356, // 0x7694 06-ew/trial/sephirot-un.ts : SephirotUn Chesed Buster
		30404, // 0x76C4 06-ew/dungeon/another_sildihn_subterrane-savage.ts : ASSS Firesteel Fracture
		30448, // 0x76F0 06-ew/raid/p5n.ts : P5N Crunch
		30449, // 0x76F1 06-ew/raid/p5n.ts : P5N Toxic Crunch
		30493, // 0x771D 06-ew/raid/p5s.ts : P5S Venomous Mass
		30507, // 0x772B 06-ew/dungeon/the_sildihn_subterrane.ts : Sildihn Silkie Carpet Buster
		30543, // 0x774F 06-ew/dungeon/another_sildihn_subterrane.ts : ASS Carpet Beater
		30578, // 0x7772 06-ew/dungeon/another_sildihn_subterrane-savage.ts : ASSS Carpet Beater
		30644, // 0x77B4 06-ew/dungeon/another_sildihn_subterrane-savage.ts : ASSS Mighty Smite
		30774, // 0x7836 06-ew/raid/p7s.ts : P7S Condensed Aero II
		30794, // 0x784A 06-ew/raid/p5s.ts : P5S Toxic Crunch
		30858, // 0x788A 06-ew/raid/p6s.ts : P6S Chelic Synergy
		30984, // 0x7908 06-ew/raid/p8n.ts : P8N Flameviper
		31045, // 0x7945 06-ew/raid/p8s.ts : P8S Flameviper
		31074, // 0x7962 06-ew/dungeon/another_sildihn_subterrane.ts : ASS Deracinator
		31098, // 0x797A 06-ew/dungeon/another_sildihn_subterrane-savage.ts : ASSS Deracinator
		31118, // 0x798E 06-ew/dungeon/lapis_manalis.ts : Lapis Manalis Cagnazzo Void Torrent
		31304, // 0x7A48 06-ew/alliance/euphrosyne.ts : Euphrosyne Althyk Petrai
		31391, // 0x7A9F 06-ew/dungeon/lapis_manalis.ts : Lapis Manalis Galatea Magna Dark Harvest
		31422, // 0x7ABE 06-ew/deepdungeon/eureka_orthos_floors_71-80.ts : EO 71-80 Proto-Kaliya Resonance
		31445, // 0x7AD5 06-ew/deepdungeon/eureka_orthos_floors_61-70.ts : EO 61-70 Aeturna Steel Claw
		31979, // 0x7CEB 06-ew/trial/rubicante.ts : Rubicante Shattering Heat
		32045, // 0x7D2D 06-ew/trial/rubicante-ex.ts : RubicanteEx Shattering Heat
		32046, // 0x7D2E 06-ew/trial/rubicante-ex.ts : RubicanteEx Dualfire Not You
		32055, // 0x7D37 06-ew/alliance/euphrosyne.ts : Euphrosyne Behemoth Localized Maelstrom
		32057, // 0x7D39 06-ew/alliance/euphrosyne.ts : Euphrosyne Ktenos Sweeping Gouge
		32060, // 0x7D3C 06-ew/alliance/euphrosyne.ts : Euphrosyne Colossus Rapid Sever
		32120, // 0x7D78 06-ew/alliance/euphrosyne.ts : Euphrosyne Halone Spears Three; 06-ew/alliance/euphrosyne.ts : Euphrosyne Halone Spears Three Not You
		32149, // 0x7D95 06-ew/trial/rubicante.ts : Rubicante Dualfire Not Target
		32190, // 0x7DBE 06-ew/trial/sophia-un.ts : SophiaUN Tank Buster
		32200, // 0x7DC8 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Gymnasiou Leon Pounce
		32206, // 0x7DCE 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Gymnasiou Tigris Frumious Jaws
		32211, // 0x7DD3 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Gymnasiou Pithekos Sweeping Gouge
		32218, // 0x7DDA 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Gymnasiou Satyros Dread Dive
		32222, // 0x7DDE 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Gymnasiou Megakantha Vine Whip
		32228, // 0x7DE4 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Gymnasiou Triton Protolithic Puncture
		32245, // 0x7DF5 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Gymnasiou Styphnolobion Rake
		32255, // 0x7DFF 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Gymnasiou Meganereis Ceras
		32265, // 0x7E09 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Gymnasiou Sphinx Scratch
		32275, // 0x7E13 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Gymnasiou Acheloios Deadly Hold
		32290, // 0x7E22 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Lampas Chrysine Lightburst
		32297, // 0x7E29 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Gymnasiou Mandragoras Ram
		32306, // 0x7E32 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Lyssa Chrysine Skull Dasher
		32330, // 0x7E4A 06-ew/map/the_shifting_gymnasion_agonon.ts : Shifting Gymnasion Agonon Narkissos Lash
		32362, // 0x7E6A 06-ew/ultimate/the_omega_protocol.ts : TOP Solar Ray You
		32363, // 0x7E6B 06-ew/ultimate/the_omega_protocol.ts : TOP Solar Ray You
		32854, // 0x8056 06-ew/dungeon/mount_rokkon.ts : Rokkon Enenra Snuff
		33073, // 0x8131 06-ew/raid/p9n.ts : P9N Ascendant Fist
		33105, // 0x8151 06-ew/raid/p9s.ts : P9S Duality of Death
		33135, // 0x816F 06-ew/raid/p9s.ts : P9S Ascendant Fist
		33327, // 0x822F 06-ew/raid/p11s.ts : P11S Dike
		33328, // 0x8230 06-ew/raid/p11s.ts : P11S Dike
		33345, // 0x8241 06-ew/dungeon/aetherfont.ts : Aetherfont Lyngbakr Sonic Bloop
		33368, // 0x8258 06-ew/dungeon/aetherfont.ts : Aetherfont Arkas Ripper Claw
		33400, // 0x8278 06-ew/raid/p10n.ts : P10N Soul Grasp
		33493, // 0x82D5 06-ew/raid/p12n.ts : P12N Glaukopis
		33532, // 0x82FC 06-ew/raid/p12s.ts : P12S Glaukopis First Cleave
		33562, // 0x831A 06-ew/raid/p12s.ts : P12S Palladian Grasp
		33705, // 0x83A9 06-ew/dungeon/mount_rokkon.ts : Rokkon Yozakura Glory Neverlasting
		33782, // 0x83F6 06-ew/dungeon/mount_rokkon.ts : Rokkon Shishio Splitting Cry
		33819, // 0x841B 06-ew/dungeon/another_mount_rokkon.ts : AMR Shishio Splitting Cry
		33858, // 0x8442 06-ew/dungeon/another_mount_rokkon-savage.ts : AMRS Shishio Splitting Cry
		33964, // 0x84AC 06-ew/trial/golbez.ts : Golbez Void Meteor
		33965, // 0x84AD 06-ew/trial/golbez-ex.ts : GolbezEx Void Meteor
		34046, // 0x84FE 06-ew/dungeon/mount_rokkon.ts : Rokkon Gorai Torching Torment
		34098, // 0x8532 06-ew/dungeon/another_mount_rokkon-savage.ts : AMRS Gorai Torching Torment; 06-ew/dungeon/another_mount_rokkon.ts : AMR Gorai Torching Torment
		34166, // 0x8576 06-ew/trial/zurvan-un.ts : ZurvanUN Tyrfing
		34275, // 0x85E3 06-ew/dungeon/another_mount_rokkon.ts : AMR Moko Lateral Slice
		34317, // 0x860D 06-ew/dungeon/another_mount_rokkon-savage.ts : AMRS Moko Lateral Slice
		34402, // 0x8662 06-ew/dungeon/another_mount_rokkon.ts : AMR Shishu Onmitsugashira Issen
		34420, // 0x8674 06-ew/dungeon/another_mount_rokkon-savage.ts : AMRS Shishu Onmitsugashira Issen
		34750, // 0x87BE 06-ew/dungeon/aloalo_island.ts : Aloalo Loquloqui Protective Will
		34942, // 0x887E 06-ew/dungeon/aloalo_island.ts : Aloalo Lala Strategic Strike
		34989, // 0x88AD 06-ew/dungeon/another_aloalo_island.ts : AAI Lala Strategic Strike
		35010, // 0x88C2 06-ew/dungeon/the_lunar_subterrane.ts : Lunar Subterrane Durante Arcane Edge
		35112, // 0x8928 06-ew/dungeon/aloalo_island.ts : Aloalo Statice Shocking Abandon
		35144, // 0x8948 06-ew/dungeon/another_aloalo_island.ts : AAI Statice Shocking Abandon
		35173, // 0x8965 06-ew/dungeon/another_aloalo_island-savage.ts : AAIS Statice Shocking Abandon
		35204, // 0x8984 06-ew/dungeon/the_lunar_subterrane.ts : Lunar Subterrane Dark Elf Staff Smite
		35270, // 0x89C6 06-ew/trial/thordan-un.ts : ThordanUN Heavenly Heel
		35491, // 0x8AA3 06-ew/dungeon/aloalo_island.ts : Aloalo Ketuduke Hydroblast
		35771, // 0x8BBB 06-ew/dungeon/another_aloalo_island.ts : AAI Monk Cross Attack
		35784, // 0x8BC8 06-ew/dungeon/another_aloalo_island-savage.ts : AAIS Kiwakin Sharp Strike
		35844, // 0x8C04 06-ew/dungeon/another_aloalo_island-savage.ts : AAIS Lala Strategic Strike
		35919, // 0x8C4F 06-ew/dungeon/another_aloalo_island-savage.ts : AAIS Monk Cross Attack
		35939, // 0x8C63 06-ew/dungeon/another_aloalo_island.ts : AAI Kiwakin Sharp Strike
		36000, // 0x8CA0 06-ew/trial/asura.ts : Asura Cutting Jewel
		36184, // 0x8D58 07-dt/trial/valigarmanda.ts : Valigarmanda Ice Talon
		36347, // 0x8DFB 07-dt/dungeon/ihuykatumu.ts : Ihuykatumu Apollyon Blade
		36356, // 0x8E04 07-dt/dungeon/ihuykatumu.ts : Ihuykatumu Apollyon Blade
		36437, // 0x8E55 07-dt/dungeon/origenics.ts : Origenics Ambrose Voltaic Slash
		36447, // 0x8E5F 07-dt/dungeon/skydeep-cenote.ts : SkydeepCenote Firearms Pummel
		36518, // 0x8EA6 07-dt/dungeon/origenics.ts : Origenics Herpekaris Convulsive Crush
		36595, // 0x8EF3 07-dt/dungeon/vanguard.ts : Vanguard Zander Saber Rush
		36597, // 0x8EF5 07-dt/dungeon/vanguard.ts : Vanguard Zander Shade Shot
		37162, // 0x912A 07-dt/dungeon/vanguard.ts : Vanguard Protector Rapid Thunder
		37223, // 0x9167 07-dt/raid/r2n.ts : R2N Honeyed Breeze
		37706, // 0x934A 07-dt/raid/r1n.ts : R1N Biscuit Maker
		37715, // 0x9353 07-dt/trial/zoraal-ja.ts : ZoraalJa Patricidal Pique
		37754, // 0x937A 07-dt/trial/zoraal-ja.ts : ZoraalJa Bitter Reaping
		37845, // 0x93D5 07-dt/raid/r3n.ts : R3N Knuckle Sandwich
		37923, // 0x9423 07-dt/raid/r3s.ts : R3S Knuckle Sandwich
		38037, // 0x9495 07-dt/raid/r1s.ts : R1S Biscuit Maker
		38261, // 0x9575 07-dt/map/cenote_ja_ja_gural.ts : Cenote Ja Ja Blade
		38274, // 0x9582 07-dt/map/cenote_ja_ja_gural.ts : Cenote Ja Ja Lap
		38384, // 0x95F0 07-dt/raid/r4s.ts : R4S Wicked Jolt
		38705, // 0x9731 07-dt/hunts/living_memory.ts : Hunt Mica the Magical Mu Shimmerstorm Tankbuster
		39132, // 0x98DC 07-dt/dungeon/ihuykatumu.ts : Ihuykatumu Drowsie Uppercut
		39230, // 0x993E 07-dt/trial/zoraal-ja-ex.ts : Zoraal Ja Ex Bitter Whirlwind
		39489, // 0x9A41 07-dt/hunts/urqopacha.ts : Hunt Queen Hawk Frenzied Sting
		39931, // 0x9BFB 07-dt/trial/byakko-un.ts : ByakkoUn Heavenly Strike
		40168, // 0x9CE8 07-dt/ultimate/futures_rewritten.ts : FRU P1 Powder Mark Trail
		40191, // 0x9CFF 07-dt/ultimate/futures_rewritten.ts : FRU P2 Quadruple Slap First
		40192, // 0x9D00 07-dt/ultimate/futures_rewritten.ts : FRU P2 Quadruple Slap Second
		40502, // 0x9E36 07-dt/alliance/cloud_of_darkness_chaotic.ts : Cloud Chaotic Excruciate
		40619, // 0x9EAB 07-dt/dungeon/yuweyawata.ts : Yuweyawata Lunipyati Slabber
		40658, // 0x9ED2 07-dt/dungeon/yuweyawata.ts : Yuweyawata Overseer Kanilokka Dark Souls
		40807, // 0x9F67 07-dt/alliance/jeuno-first-walk.ts : Jeuno First Walk Shadow Lord Unbridled Rage Call
		40855, // 0x9F97 07-dt/alliance/jeuno-first-walk.ts : Jeuno First Walk Fafnir Sharp Spike Call
		40970, // 0xA00A 07-dt/trial/queen-eternal-ex.ts : QueenEternal Ex Prosecution of War
		41078, // 0xA076 07-dt/alliance/jeuno-first-walk.ts : Jeuno First Walk Angels CloudSplitter Call
		41189, // 0xA0E5 07-dt/eureka/occult_crescent_south_horn.ts : Occult Crescent Neo Garula Squash
		41301, // 0xA155 07-dt/eureka/occult_crescent_south_horn.ts : Occult Crescent Repaired Lion Scratch
		41332, // 0xA174 07-dt/eureka/occult_crescent_south_horn.ts : Occult Crescent Death Claw Dirty Nails
		41380, // 0xA1A4 07-dt/eureka/occult_crescent_south_horn.ts : Occult Crescent Hinkypunk Dread Dive
		42189, // 0xA4CD 07-dt/raid/r8s.ts : R8S Twinbite
		42548, // 0xA634 07-dt/dungeon/the_underkeep.ts : Underkeep Gargant Trap Jaws
		42641, // 0xA691 07-dt/raid/r6s.ts : R6S Color Riot
		42642, // 0xA692 07-dt/raid/r6s.ts : R6S Color Riot
		43003, // 0xA7FB 07-dt/trial/suzaku-un.ts : SuzakuUn Cremate
		43136, // 0xA880 07-dt/dungeon/the_underkeep.ts : Underkeep Soldier S0 Thunderous Slash
		43329, // 0xA941 07-dt/dungeon/mistwake.ts : Mistwake Treno Catoblepas Thunder III
		43589, // 0xAA45 07-dt/dungeon/meso-terminal.ts : Meso Terminal Executioners Relentless Torment
		43799, // 0xAB17 07-dt/dungeon/meso-terminal.ts : Meso Terminal Chirurgeon Concentrated Dose
		43824, // 0xAB30 07-dt/dungeon/meso-terminal.ts : Meso Terminal Immortal Remains Memory Of The Pyre
		45305, // 0xB0F9 07-dt/dungeon/mistwake.ts : Mistwake Thundergust Griffin Golden Talons
		45356, // 0xB12C 07-dt/dungeon/mistwake.ts : Mistwake Treno Amdusias Shockbolt
		45359, // 0xB12F 07-dt/trial/tsukuyomi-un.ts : TsukuyomiUn Torment
		45418, // 0xB16A 07-dt/trial/tsukuyomi-un.ts : TsukuyomiUn Torment
		46123, // 0xB42B 07-dt/raid/r11s.ts : R11S Great Wall of Fire
		46373, // 0xB525 07-dt/raid/r12s.ts : R12S Esoteric Finisher
		47881, // 0xBB09 07-dt/ultimate/dancing_mad.ts : DMU P3 Thunder III Tankbuster
		49740, // 0xC24C 07-dt/ultimate/dancing_mad.ts : DMU P2 Ultimate Embrace
		50021, // 0xC365 07-dt/trial/enuo-ex.ts : EnuoEx Weight of Nothing
		50296, // 0xC478 07-dt/trial/shinryu-un.ts : ShinryuUn Tera Slash
		50722, // 0xC622 07-dt/ultimate/dancing_mad.ts : DMU P1 Hyperdrive
	];
}
